-- Contas e caixas
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - financial_accounts
--   - account_entries
--   - account_transfers
-- O banco é exclusivo por organização; não existe coluna tenant_id.
