-- Contratos e recorrência
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - service_contracts
--   - contract_cycles
--   - contract_adjustments
--   - financial_titles
-- O banco é exclusivo por organização; não existe coluna tenant_id.
