-- Visão geral
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - products
--   - stock_movements
--   - sales
--   - financial_titles
-- O banco é exclusivo por organização; não existe coluna tenant_id.
