-- Biblioteca de mídias
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - media_assets
--   - tenant_audit_events
--   - products
-- O banco é exclusivo por organização; não existe coluna tenant_id.
