-- DRE, orçamento e metas
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - cost_centers
--   - budgets
--   - budget_lines
--   - business_goals
-- O banco é exclusivo por organização; não existe coluna tenant_id.
