-- Produtos e serviços
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - products
--   - categories
--   - product_prices
-- O banco é exclusivo por organização; não existe coluna tenant_id.
