-- Central de relatórios
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - report_definitions
--   - report_runs
--   - report_exports
-- O banco é exclusivo por organização; não existe coluna tenant_id.
