-- Vendas e despesas
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - sales
--   - sale_items
--   - operating_expenses
-- O banco é exclusivo por organização; não existe coluna tenant_id.
