-- Ordens de serviço
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - service_orders
--   - service_order_items
--   - service_checklist_items
--   - service_order_history
--   - sales
--   - warehouse_balances
--   - financial_titles
-- O banco é exclusivo por organização; não existe coluna tenant_id.
