-- Fornecedores
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - suppliers
--   - supplier_contacts
--   - supplier_products
--   - supplier_scores
-- O banco é exclusivo por organização; não existe coluna tenant_id.
