-- Usuários e acessos
-- Mapa documental. NÃO aplicar este arquivo no banco.
-- Fontes executáveis: prisma/tenant/schema.prisma e prisma/tenant/migrations/.
-- Tabelas usadas por este módulo:
--   - tenant_user_profiles
--   - tenant_roles
--   - organization_invites
--   - memberships
--   - sessions
-- O banco é exclusivo por organização; não existe coluna tenant_id.
