import { currentOrganization, tenantDb } from "@/db";
import { AuthError, authErrorResponse } from "@/lib/auth";
import { assertSameOrigin } from "@/lib/erp/customer-input";
import { assertTenantPermission } from "@/lib/erp/permissions";
import { assertTenantWriteAccess } from "@/lib/tenant-access";
import { createPosT2BoundaryIdempotencyKey, toPosT2BoundaryIdempotencyKey, writePosT2WebhookBoundary } from "@/lib/erp/pos-t2-boundary";
import { IntegrationError, objectValue, persistentRateLimit } from "@/lib/integrations/core";
import { privateJson, readIntegrationJson } from "@/lib/integrations/http";
import { enqueueWebhook, serializeDelivery, serializeEndpoint, storeWebhookSecret, validateEndpointInput, webhookSecret } from "@/lib/integrations/webhooks";
import { unexpectedErrorResponse } from "@/lib/http-security";

async function context(write = false) { const organization = await currentOrganization(), access = await assertTenantPermission(organization.id, write ? "integrations.write" : "integrations.read"); if (write) await assertTenantWriteAccess(organization.id); return { organization, access, db: await tenantDb(organization.id) }; }
export async function GET(request: Request) { try { const { db } = await context(), query = new URL(request.url).searchParams, endpointId = query.get("endpoint_id") || undefined, state = query.get("state") || undefined; const endpoints = (await db.integrationWebhookEndpoint.findMany({ where: { supersededAt: null }, include: { _count: { select: { deliveries: true } } }, orderBy: { createdAt: "desc" } })).map(serializeEndpoint), deliveries = (await db.integrationWebhookDelivery.findMany({ where: { ...(endpointId ? { endpointId } : {}), ...(state ? { state } : {}) }, include: { endpoint: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 100 })).map(serializeDelivery); return privateJson({ endpoints, deliveries }); } catch (error) { return fail(error); } }
export async function POST(request: Request) { try { assertSameOrigin(request); const ctx = await context(true), body = await readIntegrationJson(request); await persistentRateLimit(ctx.db, `${ctx.access.user.id}:webhooks`, 30, 60); if (body.action === "emit") { const topic = String(body.topic || ""), result = await enqueueWebhook(ctx.db, topic, objectValue(body.payload)); return privateJson(result, { status: 202 }); } const input = await validateEndpointInput(body); if (!input.topic) throw new IntegrationError("Tópico obrigatório."); const topic = input.topic, secret = webhookSecret(), stored = storeWebhookSecret(secret), idempotencyKey = boundaryKey(body); const endpoint = await ctx.db.$transaction(async tx => { const result = await writePosT2WebhookBoundary(tx, { action: "create", logicalId: null, expectedVersion: null, expectedConfigHash: null, projection: { apiVersion: input.apiVersion, deliveryUrl: input.deliveryUrl, name: input.name, secretCipher: stored.secretCipher, secretPreview: stored.secretPreview, status: input.status as "active" | "paused" | "disabled", topic }, actorUserId: ctx.access.user.id, idempotencyKey }); const saved = await tx.integrationWebhookEndpoint.findUniqueOrThrow({ where: { id: result.endpointId } }); await tx.integrationAuditLog.create({ data: { userId: ctx.access.user.id, action: "create", targetType: "webhook", targetId: saved.id, afterData: serializeEndpoint(saved) } }); return saved; }, { isolationLevel: "Serializable", maxWait: 10_000, timeout: 30_000 }); return privateJson({ endpoint: serializeEndpoint(endpoint), secret }, { status: 201 }); } catch (error) { return fail(error); } }
function boundaryKey(body: Record<string, unknown>) { const value = String(body.idempotency_key || body.idempotencyKey || ""); return value ? toPosT2BoundaryIdempotencyKey(value) : createPosT2BoundaryIdempotencyKey(); }
function fail(error: unknown) { if (error instanceof IntegrationError) return privateJson({ error: error.message }, { status: error.status }); if (error instanceof AuthError) return authErrorResponse(error); return unexpectedErrorResponse("erp.webhooks",error); }
