export const ERP_MODULES = [
  module(
    "dashboard",
    "OPERAÇÃO",
    "Visão geral",
    "⌂",
    "Painel da empresa",
    "Acompanhe vendas, estoque e prioridades do negócio.",
    "real",
  ),
  module(
    "pdv",
    "OPERAÇÃO",
    "PDV · Ponto de venda",
    "▣",
    "Ponto de venda",
    "Registre vendas e atualize o estoque automaticamente.",
    "real",
  ),
  module(
    "pos-settings",
    "OPERAÇÃO",
    "Configurações do PDV",
    "⚙",
    "Configurações do PDV",
    "Centralize caixas, terminais, periféricos, regras e saúde operacional.",
    "real",
    ["Caixas", "Terminais", "Equipamentos", "Saúde"],
    ["Leitor de código", "Impressora", "Balança", "Autoatendimento"],
    "Filial → caixa → terminal → equipamento → monitoramento",
  ),
  module(
    "sales",
    "OPERAÇÃO",
    "Vendas e despesas",
    "↗",
    "Vendas e despesas",
    "Centralize receitas, vendas e despesas operacionais.",
    "real",
  ),
  module(
    "products",
    "OPERAÇÃO",
    "Produtos e serviços",
    "□",
    "Produtos e serviços",
    "Gerencie preços, custos, categorias e disponibilidade.",
    "real",
  ),
  module(
    "stock",
    "OPERAÇÃO",
    "Movimentações",
    "⇄",
    "Movimentações de estoque",
    "Controle entradas, saídas e saldos de cada produto.",
    "real",
  ),
  module(
    "invoices",
    "OPERAÇÃO",
    "Entrada por NF-e",
    "⇧",
    "Entrada por NF-e",
    "Importe XML, confira itens e lance estoque e financeiro.",
    "real",
    ["Notas importadas", "Itens conferidos", "Prontas", "Recebidas"],
    ["NF-e 45891", "NF-e 45877", "XML aguardando conferência"],
    "XML → conferência → custo → estoque → contas a pagar",
  ),

  module(
    "orders",
    "COMERCIAL",
    "Orçamentos e pedidos",
    "▣",
    "Orçamentos e pedidos",
    "Da proposta ao faturamento, com estoque, aprovação e recebível.",
    "real",
    ["Pipeline", "A aprovar", "A concluir", "Conversão"],
    [
      "Orçamento para Transportes Oeste",
      "Pedido balcão aprovado",
      "Pedido B2B em separação",
    ],
    "Orçamento → pedido → estoque → venda → financeiro",
  ),
  module(
    "crm",
    "COMERCIAL",
    "CRM e oportunidades",
    "◎",
    "CRM e oportunidades",
    "Leads, tarefas, propostas e histórico de etapas.",
    "real",
    ["Pipeline", "Tarefas", "Previsão", "Conversão"],
    ["Frota São Miguel", "Oficina do Vale", "Carla Mendes"],
    "Lead → qualificação → proposta → negociação → ganho",
  ),
  module(
    "contracts",
    "COMERCIAL",
    "Contratos e recorrência",
    "▤",
    "Contratos e assinaturas",
    "Vigência, reajustes, recorrência, SLA e ciclos financeiros.",
    "real",
    ["MRR", "Vigentes", "Ciclos", "SLA"],
    ["Plano Frota", "Contrato Auto Center", "Renovação anual"],
    "Contrato → ciclo → conta a receber → comunicação",
  ),
  module(
    "service-orders",
    "COMERCIAL",
    "Ordens de serviço",
    "⚙",
    "Ordens de serviço",
    "Agenda, checklist, peças, serviços, garantia e faturamento.",
    "real",
    ["Abertas", "Em execução", "Concluídas", "Garantias"],
    ["Revisão Fiat Strada", "Orçamento VW T-Cross", "Triagem Chevrolet Onix"],
    "Agenda → OS → estoque → venda → financeiro",
  ),

  module(
    "purchases",
    "SUPRIMENTOS",
    "Compras e cotações",
    "◈",
    "Compras e cotações",
    "Solicitação, cotação, pedido, recebimento e contas a pagar.",
    "real",
    ["Em cotação", "A receber", "Economia", "Lead time"],
    [
      "Reposição de lubrificantes",
      "Pedido Auto Peças XYZ",
      "Recebimento Distribuidora ABC",
    ],
    "Estoque mínimo → cotação → pedido → NF-e",
  ),
  module(
    "inventory",
    "SUPRIMENTOS",
    "Inventário e depósitos",
    "▦",
    "Inventário e depósitos",
    "Contagem física, saldos por local, transferências e razão auditável.",
    "real",
    ["Depósitos", "Divergências", "Transferências", "Custo armazenado"],
    ["Estoque principal", "Estoque de reserva", "Contagem física"],
    "Depósito → contagem → ajuste → razão de estoque",
  ),
  module(
    "production",
    "SUPRIMENTOS",
    "Produção e kits",
    "⚙",
    "Produção, kits e composição",
    "Fichas técnicas, materiais, custo real, perdas e produto acabado.",
    "real",
    ["Fichas", "Ordens abertas", "Concluídas", "Custo real"],
    ["Kit revisão Premium", "Kit freio dianteiro", "Combo troca de óleo"],
    "Ficha → consumo → produção → custo e estoque",
  ),

  module(
    "marketplaces",
    "OMNICANAL",
    "Canais e marketplaces",
    "▦",
    "Canais e marketplaces",
    "Pedidos, anúncios, preços, taxas e estoque sincronizados.",
    "real",
    ["GMV", "Pedidos novos", "Sincronização", "Anúncios com erro"],
    ["Pedido Mercado Livre", "Pedido Shopee", "Pedido loja virtual"],
    "Canal → pedido → estoque → fiscal → expedição",
  ),
  module(
    "logistics",
    "OMNICANAL",
    "Expedição e logística",
    "⇄",
    "Expedição e logística",
    "Picking, packing, etiquetas, rastreio, fretes e ocorrências.",
    "real",
    ["A despachar", "No prazo", "Frete médio", "Ocorrências"],
    ["Expedição WEB-4821", "Conferência MLB-784", "Separação B2B-1048"],
    "Pedido → picking → packing → transportadora",
  ),

  module(
    "finance",
    "FINANCEIRO",
    "Contas a pagar/receber",
    "R$",
    "Contas a pagar e receber",
    "Vencimentos, baixas, parcelas e centros de custo.",
    "real",
    ["A receber", "A pagar", "Vencido", "Saldo projetado"],
    [
      "Fornecedor Distribuidora ABC",
      "Recebível venda #1046",
      "Despesa de energia",
    ],
    "Operação → título → baixa → fluxo de caixa",
  ),
  module(
    "cash-close",
    "FINANCEIRO",
    "Fechamento de caixa",
    "◷",
    "Fechamento de caixa",
    "Abertura, sangria, suprimento, conferência e fechamento do PDV.",
    "real",
    ["Caixas abertos", "Movimento hoje", "Diferença", "Fechados"],
    ["Caixa principal aberto", "Fechamento #0031", "Sangria operacional"],
    "PDV → sessão → conferência → fechamento",
  ),
  module(
    "accounts",
    "FINANCEIRO",
    "Contas e caixas",
    "▣",
    "Contas e caixas",
    "Saldos, transferências e disponibilidade financeira.",
    "real",
    ["Saldo total", "Bancos", "Caixas", "Transferências"],
    ["Caixa principal", "Banco Inter PJ", "Carteira Pix"],
    "Conta → lançamento → conciliação → saldo",
  ),
  module(
    "reconciliation",
    "FINANCEIRO",
    "Conciliação bancária",
    "✓",
    "Conciliação bancária",
    "Extratos, Pix, boletos, cartões, CNAB e baixa assistida.",
    "real",
    ["A conciliar", "Conciliado hoje", "Divergências", "Automação"],
    ["Pix recebido", "Lote de cartão", "Pagamento de fornecedor"],
    "Banco → sugestão → conciliação → baixa",
  ),
  module(
    "planning",
    "FINANCEIRO",
    "DRE, orçamento e metas",
    "▥",
    "DRE, orçamento e metas",
    "Resultado, centros de custo, cenários e previsão de caixa.",
    "real",
    ["Receita líquida", "Margem", "Resultado", "Desvio"],
    ["Orçamento operacional", "Meta comercial", "Cenário de expansão"],
    "Operação → centros de custo → DRE → cenário",
  ),

  module(
    "fiscal",
    "FISCAL",
    "Central fiscal",
    "NF",
    "Central fiscal",
    "NF-e, NFC-e, NFS-e, eventos, contingência e rejeições.",
    "real",
    ["Autorizadas", "Contingência", "Rejeições", "Certificado"],
    ["NF-e 000.001.284", "NFC-e 000.004.918", "NFS-e de serviço"],
    "Pedido ou OS → documento → SEFAZ/prefeitura",
  ),

  module(
    "customers",
    "CADASTROS",
    "Clientes",
    "◎",
    "Clientes",
    "Dados, endereços, crédito, histórico e relacionamento.",
    "real",
    ["Ativos", "Novos", "Recorrentes", "Inadimplentes"],
    ["João Carlos de Souza", "Transportes Oeste Ltda.", "Marcos Silva"],
    "Cliente → venda → financeiro → pós-venda",
  ),
  module(
    "suppliers",
    "CADASTROS",
    "Fornecedores",
    "◈",
    "Fornecedores",
    "Contatos, documentos, produtos vinculados e desempenho.",
    "real",
    ["Ativos", "Itens vinculados", "Pedidos abertos", "Prazo médio"],
    ["Distribuidora ABC", "Auto Peças XYZ", "Comercial São Bento"],
    "Fornecedor → cotação → compra → recebimento",
  ),
  module(
    "categories",
    "CADASTROS",
    "Categorias",
    "#",
    "Categorias",
    "Estruture catálogo, serviços e regras comerciais.",
    "real",
    ["Categorias", "Produtos", "Serviços", "Sem categoria"],
    ["Lubrificantes", "Filtros", "Serviços"],
    "Categoria → produto → preço → relatório",
  ),
  module(
    "users",
    "CADASTROS",
    "Usuários e acessos",
    "⚙",
    "Usuários e permissões",
    "Equipes, convites seguros, perfis e matriz de acesso.",
    "real",
    ["Ativos", "Convites", "Perfis", "Sessões"],
    ["Administrador", "Vendas e atendimento", "Estoque e compras"],
    "Convite → aceite → membership → perfil → autorização",
  ),

  module(
    "reports",
    "GESTÃO",
    "Central de relatórios",
    "▥",
    "Central de relatórios",
    "Indicadores reais de vendas, estoque e operação.",
    "real",
  ),
  module(
    "library",
    "GESTÃO",
    "Biblioteca de mídias",
    "image",
    "Biblioteca de mídias",
    "Organize imagens e documentos e reutilize arquivos nos cadastros.",
    "real",
    ["Arquivos", "Imagens", "Documentos", "Armazenamento"],
    ["Identidade visual", "Catálogo de produtos", "Documentos"],
    "Upload seguro → organização → seleção → reutilização",
  ),
  module(
    "branches",
    "GESTÃO",
    "Empresas e filiais",
    "▦",
    "Empresas e filiais",
    "CNPJs, depósitos, regras fiscais e consolidação.",
    "real",
    ["Unidades", "CNPJs", "Depósitos", "Pendências"],
    ["Matriz", "Filial Centro", "Centro de distribuição"],
    "Filial → perfis → fiscal e estoque → consolidação",
  ),
  module(
    "automations",
    "GESTÃO",
    "Automações",
    "✦",
    "Regras e automações",
    "Gatilhos, condições, aprovações, webhooks e execuções.",
    "real",
    ["Ativas", "Execuções", "Economia", "Falhas"],
    [
      "Reposição de estoque",
      "Cobrança no vencimento",
      "Emissão fiscal automática",
    ],
    "Evento → condição → ação → auditoria",
  ),
  module(
    "activities",
    "GESTÃO",
    "Atividades e auditoria",
    "◉",
    "Atividades e auditoria",
    "Ações, alterações e evidências imutáveis do tenant.",
    "real",
    ["Eventos hoje", "Atores", "Correlações", "Exportações"],
    ["Compra recebida", "Título liquidado", "Inventário concluído"],
    "Usuário → ação → correlação → evidência imutável",
  ),
  module(
    "privacy",
    "GESTÃO",
    "Privacidade e LGPD",
    "◇",
    "Privacidade e LGPD",
    "Bases legais, titulares, retenção, incidentes e evidências.",
    "real",
    ["Solicitações", "No prazo", "Dados mapeados", "Riscos"],
    ["Solicitação de acesso", "Correção cadastral", "Política de retenção"],
    "Titular → validação → execução → evidência",
  ),
  module(
    "integrations",
    "GESTÃO",
    "Integrações",
    "⇄",
    "Integrações",
    "Providers, credenciais, roteamento, webhooks e monitoramento.",
    "real",
    ["Providers", "Saúde", "Fila", "Entrega"],
    ["Mensageria", "Pagamentos", "Marketplaces", "Armazenamento"],
    "Credencial → provider → contexto → fila → observabilidade",
  ),
  module(
    "payments",
    "GESTÃO",
    "Pagamentos e recebimentos",
    "R$",
    "Pagamentos e recebimentos",
    "Contas adquirentes, Pix, links, TEF, SmartPOS e roteamento por caixa.",
    "real",
    ["Providers", "Contas", "Rotas", "Conciliação"],
    ["Mercado Pago", "Banco Inter", "Cielo", "Stone"],
    "Conta → método → canal → filial/caixa → conciliação",
  ),
  module(
    "transactional-email",
    "GESTÃO",
    "E-mails transacionais",
    "✉",
    "E-mails transacionais",
    "Catálogo versionado, SMTP, testes, variáveis e histórico de entrega.",
    "real",
    ["Eventos", "Publicados", "Fila", "Falhas"],
    ["Acesso", "Pedidos", "Fiscal", "Financeiro"],
    "Evento → template publicado → SMTP → entrega → auditoria",
  ),
  module(
    "ai-integrations",
    "GESTÃO",
    "Inteligência artificial",
    "✦",
    "Inteligência artificial",
    "OpenAI gerenciada ou BYOK, modelos permitidos, orçamento e uso.",
    "real",
    ["Modo", "Modelos", "Orçamento", "Consumo"],
    ["OpenAI Responses API", "Chave própria", "Limites"],
    "Recurso → política → OpenAI → medição → auditoria",
  ),
  module(
    "settings",
    "GESTÃO",
    "Configurações",
    "⚙",
    "Configurações",
    "Empresa, fiscal, PDV, notificações e integrações do tenant.",
    "real",
    ["Empresa", "Fiscal", "PDV", "Integrações"],
    ["Dados da empresa", "Configuração fiscal", "Preferências do sistema"],
    "Configuração → validação → aplicação → auditoria",
  ),
] as const;

export type ErpPage = (typeof ERP_MODULES)[number]["id"];
export type ErpModule = (typeof ERP_MODULES)[number];
export const ERP_ROUTE_SLUGS: Record<ErpPage, string> = {
  dashboard: "",
  pdv: "pdv",
  "pos-settings": "configuracoes-pdv",
  sales: "vendas-despesas",
  products: "produtos-servicos",
  stock: "movimentacoes-estoque",
  invoices: "entrada-nfe",
  orders: "orcamentos-pedidos",
  crm: "crm-oportunidades",
  contracts: "contratos-recorrencia",
  "service-orders": "ordens-servico",
  purchases: "compras-cotacoes",
  inventory: "inventario-depositos",
  production: "producao-kits",
  marketplaces: "canais-marketplaces",
  logistics: "expedicao-logistica",
  finance: "contas-pagar-receber",
  "cash-close": "fechamento-caixa",
  accounts: "contas-caixas",
  reconciliation: "conciliacao-bancaria",
  planning: "dre-orcamento-metas",
  fiscal: "central-fiscal",
  customers: "clientes",
  suppliers: "fornecedores",
  categories: "categorias",
  users: "usuarios",
  reports: "relatorios",
  library: "biblioteca",
  branches: "empresas-filiais",
  automations: "automacoes",
  activities: "atividades-auditoria",
  privacy: "privacidade-lgpd",
  integrations: "integracoes",
  payments: "pagamentos-recebimentos",
  "transactional-email": "emails-transacionais",
  "ai-integrations": "inteligencia-artificial",
  settings: "configuracoes",
};
export const ERP_SECTIONS = [
  ...new Set(ERP_MODULES.map((item) => item.section)),
];
export function isErpPage(value: string): value is ErpPage {
  return ERP_MODULES.some((item) => item.id === value);
}
export function erpModule(value: ErpPage) {
  return ERP_MODULES.find((item) => item.id === value)!;
}
export function erpPageFromRoute(value: string): ErpPage | undefined {
  const localized = (
    Object.entries(ERP_ROUTE_SLUGS) as Array<[ErpPage, string]>
  ).find(([, slug]) => slug === value)?.[0];
  return localized || (isErpPage(value) ? value : undefined);
}
export function erpRoute(value: ErpPage) {
  const slug = ERP_ROUTE_SLUGS[value];
  return slug ? `/erp/${slug}` : "/erp";
}

function module<const Id extends string, const Section extends string>(
  id: Id,
  section: Section,
  label: string,
  icon: string,
  title: string,
  description: string,
  implementation: "real",
  metrics: readonly string[] = [],
  samples: readonly string[] = [],
  flow = "",
) {
  return {
    id,
    section,
    label,
    icon,
    title,
    description,
    implementation,
    metrics,
    samples,
    flow,
  } as const;
}
