import { SUPPLIER_CATEGORIES, SUPPLIER_HOMOLOGATION, SUPPLIER_RISKS, SupplierInputError } from "./supplier-input";

export type SupplierQuery = { search: string; status: string; category: string; risk: string; homologation: string; attention: string; sort: "name" | "recent" | "spend" | "performance"; page: number; limit: number; format: "json" | "csv" };

export function parseSupplierQuery(parameters: URLSearchParams): SupplierQuery {
  return {
    search: String(parameters.get("search") || "").trim().slice(0, 100), status: optionalChoice(parameters.get("status"), ["active", "inactive"]),
    category: optionalChoice(parameters.get("category"), SUPPLIER_CATEGORIES), risk: optionalChoice(parameters.get("risk"), SUPPLIER_RISKS),
    homologation: optionalChoice(parameters.get("homologation"), SUPPLIER_HOMOLOGATION), attention: optionalChoice(parameters.get("attention"), ["documents", "tasks", "incomplete", "pending"]),
    sort: optionalChoice(parameters.get("sort"), ["name", "recent", "spend", "performance"] as const) || "name", format: parameters.get("format") === "csv" ? "csv" : "json",
    page: integer(parameters.get("page"), 1, 10_000), limit: integer(parameters.get("limit"), 25, 100),
  };
}

export function supplierPerformance(value?: { qualityScore: number; deliveryScore: number; commercialScore: number; complianceScore: number } | null) { return value ? Math.round((value.qualityScore * 0.3) + (value.deliveryScore * 0.3) + (value.commercialScore * 0.15) + (value.complianceScore * 0.25)) : 0; }
export function supplierHealth(supplier: { email?: string | null; phone?: string | null; document?: string | null; addresses?: unknown[]; homologationStatus: string; riskRating: string; status: string; expiringDocuments: number; pendingTasks: number; performanceScore: number }) { let score = 100; const issues: string[] = []; if (!supplier.email) { score -= 12; issues.push("sem e-mail"); } if (!supplier.phone) { score -= 12; issues.push("sem telefone"); } if (!supplier.document) { score -= 20; issues.push("sem documento fiscal"); } if (!supplier.addresses?.length) { score -= 12; issues.push("sem endereço"); } if (supplier.homologationStatus !== "approved") { score -= supplier.homologationStatus === "conditional" ? 10 : 22; issues.push("homologação pendente"); } if (["high", "blocked"].includes(supplier.riskRating)) { score -= 18; issues.push("risco elevado"); } if (supplier.expiringDocuments) { score -= 15; issues.push("documentos vencidos ou próximos"); } if (supplier.pendingTasks) { score -= 5; issues.push("tarefas pendentes"); } if (supplier.performanceScore > 0 && supplier.performanceScore < 60) { score -= 15; issues.push("desempenho baixo"); } if (supplier.status === "inactive") score -= 5; return { score: Math.max(0, score), issues }; }
export function duplicateSupplierGroups(items: Array<{ id: number; name: string; email: string | null; phone: string | null }>) { const groups = new Map<string, Array<{ id: number; name: string }>>(); for (const item of items) for (const key of [item.email ? `email:${item.email.trim().toLowerCase()}` : "", item.phone ? `phone:${item.phone.replace(/\D/g, "")}` : ""].filter((key) => key.length > 9)) groups.set(key, [...(groups.get(key) || []), { id: item.id, name: item.name }]); return [...groups.entries()].filter(([, values]) => values.length > 1).slice(0, 20).map(([key, items]) => ({ field: key.startsWith("email:") ? "E-mail" : "Telefone", value: mask(key.slice(key.indexOf(":") + 1), key.startsWith("email:")), items })); }
export function supplierCsv(items: Array<Record<string, unknown>>) { const headings = ["Nome", "Nome fantasia", "Tipo", "CPF/CNPJ", "E-mail", "Telefone", "Status", "Categoria", "Homologação", "Risco", "Comprador", "Cidade", "UF", "Prazo pagamento", "Lead time", "Pedido mínimo", "Compras", "Em aberto", "Performance", "Atualização"], keys = ["name", "tradeName", "type", "document", "email", "phone", "status", "category", "homologationStatus", "riskRating", "buyer", "city", "state", "paymentTermsDays", "deliveryLeadTimeDays", "minimumOrder", "spend", "openPayables", "performanceScore", "updatedAt"]; return `\uFEFF${[headings, ...items.map((item) => keys.map((key) => item[key]))].map((row) => row.map(csvCell).join(";")).join("\r\n")}`; }
export function parseSupplierCsv(source: string) { if (!source.trim()) throw new SupplierInputError("O arquivo CSV está vazio."); if (new TextEncoder().encode(source).byteLength > 2_097_152) throw new SupplierInputError("O CSV excede o limite de 2 MB."); const first = source.split(/\r?\n/, 1)[0] || "", delimiter = occurrences(first, ";") >= occurrences(first, ",") ? ";" : ",", table = parseDelimited(source, delimiter).filter((row) => row.some((cell) => cell.trim())); if (table.length < 2) throw new SupplierInputError("O CSV deve conter cabeçalho e ao menos um fornecedor."); if (table.length > 501) throw new SupplierInputError("Importe no máximo 500 fornecedores por arquivo."); const aliases: Record<string, string> = { nome: "name", razao_social: "name", name: "name", nome_fantasia: "tradeName", fantasia: "tradeName", cpf_cnpj: "document", cnpj: "document", documento: "document", document: "document", email: "email", telefone: "phone", categoria: "category", origem: "origin", comprador: "buyer", risco: "riskRating", homologacao: "homologationStatus", regime_tributario: "taxRegime", inscricao_estadual: "stateRegistration", inscricao_municipal: "municipalRegistration", site: "website", condicao_pagamento: "paymentTerms", prazo_pagamento_dias: "paymentTermsDays", lead_time_dias: "deliveryLeadTimeDays", pedido_minimo: "minimumOrder", cep: "zip", logradouro: "street", rua: "street", numero: "number", complemento: "complement", bairro: "district", cidade: "city", uf: "state" }, headers = table[0].map((header) => aliases[normalizeHeader(header)] || ""); if (!headers.includes("name") || !headers.includes("document")) throw new SupplierInputError("O CSV precisa das colunas nome e cpf_cnpj."); return table.slice(1).map((row, index) => { const value: Record<string, string> = {}; headers.forEach((key, column) => { if (key) value[key] = String(row[column] || "").trim(); }); return { row: index + 2, value }; }); }
function optionalChoice<T extends string>(value: string | null, allowed: readonly T[]): T | "" { if (!value) return ""; if (!allowed.includes(value as T)) throw new SupplierInputError("Filtro de fornecedores inválido."); return value as T; }
function integer(value: string | null, fallback: number, maximum: number) { const parsed = Number(value || fallback); if (!Number.isInteger(parsed) || parsed < 1) throw new SupplierInputError("Paginação inválida."); return Math.min(parsed, maximum); }
function mask(value: string, email: boolean) { if (email) { const [name, domain] = value.split("@"); return `${name.slice(0, 2)}***@${domain || ""}`; } return value.length > 4 ? `${"*".repeat(value.length - 4)}${value.slice(-4)}` : "****"; }
function csvCell(value: unknown) { const text = value instanceof Date ? value.toISOString() : String(value ?? ""); return `"${text.replace(/"/g, '""').replace(/^[=+\-@]/, "'$&")}"`; }
function occurrences(value: string, character: string) { return [...value].filter((item) => item === character).length; }
function normalizeHeader(value: string) { return value.trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
function parseDelimited(source: string, delimiter: string) { const rows: string[][] = []; let row: string[] = [], cell = "", quoted = false; for (let index = 0; index < source.length; index += 1) { const character = source[index]; if (character === '"') { if (quoted && source[index + 1] === '"') { cell += '"'; index += 1; } else quoted = !quoted; continue; } if (!quoted && character === delimiter) { row.push(cell); cell = ""; continue; } if (!quoted && (character === "\n" || character === "\r")) { if (character === "\r" && source[index + 1] === "\n") index += 1; row.push(cell); rows.push(row); row = []; cell = ""; continue; } cell += character; } if (quoted) throw new SupplierInputError("O CSV contém aspas não finalizadas."); if (cell.length || row.length) { row.push(cell); rows.push(row); } return rows; }
