import { randomUUID } from "node:crypto";
import { Prisma } from "@/generated/tenant/client";
import { currentOrganization, tenantDb } from "@/db";
import { AuthError, authErrorResponse } from "@/lib/auth";
import { LicenseDeniedError } from "@/lib/billing/license";
import { assertSameOrigin } from "@/lib/erp/customer-input";
import { supplierHealth, supplierPerformance } from "@/lib/erp/supplier-control";
import { supplierAddressInput, supplierContactInput, supplierDocumentInput, supplierEntityId, supplierEvaluationInput, supplierInput, SupplierInputError, supplierInteractionInput, supplierProductInput, supplierTagInput, supplierVersion } from "@/lib/erp/supplier-input";
import { assertTenantPermission } from "@/lib/erp/permissions";
import { assertPosMutationRequest, enforcePosRateLimit, PosHttpError, readPosJson } from "@/lib/erp/pos-http";
import { enqueueWebhook } from "@/lib/integrations/webhooks";
import { assertTenantWriteAccess } from "@/lib/tenant-access";

export const dynamic = "force-dynamic";
const NO_STORE = { "cache-control": "private, no-store, max-age=0", expires: "0", pragma: "no-cache" };
const fullInclude = {
  addresses: { orderBy: [{ primary: "desc" as const }, { label: "asc" as const }] },
  contacts: { where: { archivedAt: null }, orderBy: [{ primary: "desc" as const }, { name: "asc" as const }] },
  tagLinks: { include: { tag: true }, orderBy: { createdAt: "asc" as const } }, interactions: { orderBy: { createdAt: "desc" as const }, take: 100 },
  complianceDocuments: { orderBy: [{ expiresAt: "asc" as const }, { createdAt: "desc" as const }], take: 100 }, evaluations: { orderBy: { evaluatedAt: "desc" as const }, take: 30 },
  products: { include: { product: { select: { id: true, name: true, sku: true, unit: true, cost: true, stock: true, active: true } } }, orderBy: [{ preferred: "desc" as const }, { updatedAt: "desc" as const }] },
  purchaseOrders: { select: { id: true, number: true, status: true, expectedAt: true, dueAt: true, total: true, createdAt: true, _count: { select: { items: true, receipts: true } } }, orderBy: { createdAt: "desc" as const }, take: 50 },
  quotationOffers: { select: { id: true, total: true, leadTimeDays: true, paymentTerms: true, selected: true, createdAt: true, quotation: { select: { id: true, number: true, title: true, status: true } } }, orderBy: { createdAt: "desc" as const }, take: 30 },
  financialTitles: { where: { type: "payable" }, select: { id: true, description: true, documentNumber: true, status: true, amount: true, paidAmount: true, dueAt: true }, orderBy: { dueAt: "desc" as const }, take: 60 },
  purchaseInvoices: { select: { id: true, number: true, series: true, status: true, issueDate: true, total: true, receivedAt: true }, orderBy: { issueDate: "desc" as const }, take: 50 },
};
type Tx = Prisma.TransactionClient;
const serializable = { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, maxWait: 10_000, timeout: 30_000 } as const;

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  try {
    const organization = await currentOrganization(); await assertTenantPermission(organization.id, "suppliers.read");
    const db = await tenantDb(organization.id), id = supplierEntityId((await context.params).id), supplier = await db.supplier.findUnique({ where: { id }, include: fullInclude });
    if (!supplier) return Response.json({ error: "Fornecedor não encontrado." }, { status: 404, headers: NO_STORE });
    const now = new Date(), documentLimit = new Date(now.valueOf() + 30 * 86_400_000), [auditRows, orders, titles, overdue, invoices, pendingTasks, expiringDocuments, productCatalog] = await Promise.all([
      db.tenantAuditEvent.findMany({ where: { entityType: "supplier", entityId: String(id) }, select: { id: true, action: true, actorId: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 60 }),
      db.purchaseOrder.aggregate({ where: { supplierId: id, status: { notIn: ["draft", "cancelled"] } }, _sum: { total: true }, _count: { _all: true }, _max: { createdAt: true } }),
      db.financialTitle.aggregate({ where: { supplierId: id, type: "payable", status: { in: ["open", "partial", "overdue"] } }, _sum: { amount: true, paidAmount: true } }),
      db.financialTitle.aggregate({ where: { supplierId: id, type: "payable", status: { in: ["open", "partial", "overdue"] }, dueAt: { lt: now } }, _sum: { amount: true, paidAmount: true } }),
      db.purchaseInvoice.aggregate({ where: { supplierId: id }, _sum: { total: true }, _count: { _all: true }, _max: { issueDate: true } }), db.supplierInteraction.count({ where: { supplierId: id, completedAt: null } }),
      db.supplierDocument.count({ where: { supplierId: id, OR: [{ status: { in: ["expired", "pending", "rejected"] } }, { expiresAt: { lte: documentLimit } }] } }),
      db.product.findMany({ where: { active: true }, select: { id: true, name: true, sku: true, unit: true, cost: true }, orderBy: { name: "asc" }, take: 500 }),
    ]);
    const latestEvaluation = supplier.evaluations[0], performanceScore = supplierPerformance(latestEvaluation), metrics = { spend: orders._sum.total || 0, orders: orders._count._all, invoiceValue: invoices._sum.total || 0, invoices: invoices._count._all, openPayables: (titles._sum.amount || 0) - (titles._sum.paidAmount || 0), overduePayables: (overdue._sum.amount || 0) - (overdue._sum.paidAmount || 0), pendingTasks, expiringDocuments, performanceScore, lastPurchaseAt: later(orders._max.createdAt, invoices._max.issueDate) }, health = supplierHealth({ ...supplier, ...metrics }), audit = auditRows.map((item) => ({ ...item, id: String(item.id) }));
    return Response.json({ supplier: { ...supplier, metrics, health }, productCatalog, audit, generatedAt: now.toISOString() }, { headers: NO_STORE });
  } catch (error) { return failure(error); }
}

export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) {
  try {
    assertSameOrigin(request); assertPosMutationRequest(request);
    const organization = await currentOrganization(), access = await assertTenantPermission(organization.id, "suppliers.write"); await assertTenantWriteAccess(organization.id);
    const db = await tenantDb(organization.id), id = supplierEntityId((await context.params).id), body = await readPosJson(request, 262_144), correlationId = randomUUID(); await enforcePosRateLimit(db, access.user.id, "suppliers.mutation");
    const before = await db.supplier.findUnique({ where: { id }, include: { addresses: { where: { primary: true }, take: 1 } } });
    if (!before) return Response.json({ error: "Fornecedor não encontrado." }, { status: 404, headers: NO_STORE });
    if (body.action === "status" || body.action === "homologation") {
      const version = supplierVersion(body.version), data = body.action === "status" ? { status: body.status === "inactive" || body.status === "active" ? body.status : "" } : { homologationStatus: ["pending", "approved", "conditional", "rejected", "expired"].includes(String(body.homologationStatus)) ? String(body.homologationStatus) : "" };
      if (!Object.values(data)[0]) throw new SupplierInputError("Situação inválida.");
      const supplier = await db.$transaction(async (tx) => { await lockSupplier(tx, id); const changed = await tx.supplier.updateMany({ where: { id, version }, data: { ...data, version: { increment: 1 } } }); if (changed.count !== 1) throw conflict(); await audit(tx, access.user.id, body.action === "status" ? "supplier.status_changed" : "supplier.homologation_changed", id, correlationId, body.action === "status" ? { status: before.status } : { homologationStatus: before.homologationStatus }, data); await enqueueWebhook(tx, "supplier.updated", { id, ...data, occurred_at: new Date().toISOString(), correlation_id: correlationId }); return tx.supplier.findUniqueOrThrow({ where: { id }, include: fullInclude }); }, serializable);
      return Response.json({ supplier, correlationId }, { headers: NO_STORE });
    }
    if (body.action === "contact.create" || body.action === "contact.update") { const input = supplierContactInput(body), contactId = body.action === "contact.update" ? supplierEntityId(body.contactId, "Contato") : null; const contact = await db.$transaction(async (tx) => { if (input.primary) await tx.supplierContact.updateMany({ where: { supplierId: id, archivedAt: null }, data: { primary: false } }); if (contactId) { const changed = await tx.supplierContact.updateMany({ where: { id: contactId, supplierId: id, archivedAt: null }, data: input }); if (changed.count !== 1) throw new SupplierInputError("Contato não encontrado."); } const saved = contactId ? await tx.supplierContact.findUniqueOrThrow({ where: { id: contactId } }) : await tx.supplierContact.create({ data: { supplierId: id, ...input } }); await audit(tx, access.user.id, contactId ? "supplier.contact_updated" : "supplier.contact_created", id, correlationId, null, { contactId: saved.id, name: saved.name }); return saved; }, serializable); return Response.json({ contact, correlationId }, { status: contactId ? 200 : 201, headers: NO_STORE }); }
    if (body.action === "contact.archive") { const contactId = supplierEntityId(body.contactId, "Contato"), changed = await db.supplierContact.updateMany({ where: { id: contactId, supplierId: id, archivedAt: null }, data: { archivedAt: new Date(), primary: false } }); if (changed.count !== 1) throw new SupplierInputError("Contato não encontrado."); await recordAudit(db, access.user.id, "supplier.contact_archived", id, correlationId, { contactId }); return Response.json({ archived: true, correlationId }, { headers: NO_STORE }); }
    if (body.action === "address.upsert") { const input = supplierAddressInput(body), addressId = body.addressId ? supplierEntityId(body.addressId, "Endereço") : null; const address = await db.$transaction(async (tx) => { if (input.primary) await tx.supplierAddress.updateMany({ where: { supplierId: id }, data: { primary: false } }); if (addressId) { const changed = await tx.supplierAddress.updateMany({ where: { id: addressId, supplierId: id }, data: input }); if (changed.count !== 1) throw new SupplierInputError("Endereço não encontrado."); } const saved = addressId ? await tx.supplierAddress.findUniqueOrThrow({ where: { id: addressId } }) : await tx.supplierAddress.create({ data: { supplierId: id, ...input } }); await audit(tx, access.user.id, "supplier.address_saved", id, correlationId, null, { addressId: saved.id, label: saved.label }); return saved; }, serializable); return Response.json({ address, correlationId }, { headers: NO_STORE }); }
    if (body.action === "interaction.create") { const input = supplierInteractionInput(body), interaction = await db.supplierInteraction.create({ data: { supplierId: id, ...input, createdBy: access.user.name } }); await recordAudit(db, access.user.id, "supplier.interaction_created", id, correlationId, { interactionId: interaction.id, type: interaction.type, subject: interaction.subject }); return Response.json({ interaction, correlationId }, { status: 201, headers: NO_STORE }); }
    if (body.action === "interaction.complete") { const interactionId = supplierEntityId(body.interactionId, "Interação"), completed = body.completed !== false, changed = await db.supplierInteraction.updateMany({ where: { id: interactionId, supplierId: id }, data: { completedAt: completed ? new Date() : null } }); if (changed.count !== 1) throw new SupplierInputError("Interação não encontrada."); await recordAudit(db, access.user.id, completed ? "supplier.interaction_completed" : "supplier.interaction_reopened", id, correlationId, { interactionId }); return Response.json({ completed, correlationId }, { headers: NO_STORE }); }
    if (body.action === "document.create" || body.action === "document.update") { const input = supplierDocumentInput(body), documentId = body.action === "document.update" ? supplierEntityId(body.documentId, "Documento") : null; if (documentId) { const changed = await db.supplierDocument.updateMany({ where: { id: documentId, supplierId: id }, data: input }); if (changed.count !== 1) throw new SupplierInputError("Documento não encontrado."); } const document = documentId ? await db.supplierDocument.findUniqueOrThrow({ where: { id: documentId } }) : await db.supplierDocument.create({ data: { supplierId: id, ...input, createdBy: access.user.name } }); await recordAudit(db, access.user.id, documentId ? "supplier.document_updated" : "supplier.document_created", id, correlationId, { documentId: document.id, type: document.type, status: document.status, expiresAt: document.expiresAt?.toISOString() || null }); return Response.json({ document, correlationId }, { status: documentId ? 200 : 201, headers: NO_STORE }); }
    if (body.action === "evaluation.create") { const input = supplierEvaluationInput(body), evaluation = await db.supplierEvaluation.create({ data: { supplierId: id, ...input, evaluatedBy: access.user.name } }); await recordAudit(db, access.user.id, "supplier.evaluation_created", id, correlationId, { evaluationId: evaluation.id, score: supplierPerformance(evaluation) }); return Response.json({ evaluation, correlationId }, { status: 201, headers: NO_STORE }); }
    if (body.action === "product.upsert") { const input = supplierProductInput(body); if (!await db.product.findFirst({ where: { id: input.productId, active: true }, select: { id: true } })) throw new SupplierInputError("Produto ativo não encontrado."); const product = await db.supplierProduct.upsert({ where: { supplierId_productId: { supplierId: id, productId: input.productId } }, update: input, create: { supplierId: id, ...input } }); await recordAudit(db, access.user.id, "supplier.product_saved", id, correlationId, { productId: input.productId, preferred: input.preferred }); return Response.json({ product, correlationId }, { headers: NO_STORE }); }
    if (body.action === "product.remove") { const productId = supplierEntityId(body.productId, "Produto"), removed = await db.supplierProduct.deleteMany({ where: { supplierId: id, productId } }); if (removed.count !== 1) throw new SupplierInputError("Produto não vinculado."); await recordAudit(db, access.user.id, "supplier.product_removed", id, correlationId, { productId }); return Response.json({ removed: true, correlationId }, { headers: NO_STORE }); }
    if (body.action === "tag.add") { const input = supplierTagInput(body), tag = await db.supplierTag.upsert({ where: { name: input.name }, update: { color: input.color }, create: input }); await db.supplierTagLink.upsert({ where: { supplierId_tagId: { supplierId: id, tagId: tag.id } }, update: {}, create: { supplierId: id, tagId: tag.id } }); await recordAudit(db, access.user.id, "supplier.tag_added", id, correlationId, { tagId: tag.id, name: tag.name }); return Response.json({ tag, correlationId }, { headers: NO_STORE }); }
    if (body.action === "tag.remove") { const tagId = supplierEntityId(body.tagId, "Etiqueta"), removed = await db.supplierTagLink.deleteMany({ where: { supplierId: id, tagId } }); if (removed.count !== 1) throw new SupplierInputError("Etiqueta não vinculada."); await recordAudit(db, access.user.id, "supplier.tag_removed", id, correlationId, { tagId }); return Response.json({ removed: true, correlationId }, { headers: NO_STORE }); }

    const input = supplierInput(body), version = supplierVersion(body.version), supplier = await db.$transaction(async (tx) => { await lockSupplier(tx, id); const { address, ...profile } = input, changed = await tx.supplier.updateMany({ where: { id, version }, data: { ...profile, version: { increment: 1 } } }); if (changed.count !== 1) throw conflict(); const primary = before.addresses[0]; if (primary) await tx.supplierAddress.update({ where: { id: primary.id }, data: address }); else await tx.supplierAddress.create({ data: { supplierId: id, ...address, label: "Principal", primary: true } }); await audit(tx, access.user.id, "supplier.updated", id, correlationId, { name: before.name, document: before.document, version }, { name: input.name, document: input.document, category: input.category, homologationStatus: input.homologationStatus, version: version + 1 }); await enqueueWebhook(tx, "supplier.updated", { id, status: before.status, occurred_at: new Date().toISOString(), correlation_id: correlationId }); return tx.supplier.findUniqueOrThrow({ where: { id }, include: fullInclude }); }, serializable);
    return Response.json({ supplier, correlationId }, { headers: NO_STORE });
  } catch (error) { return failure(error); }
}

async function lockSupplier(tx: Tx, id: number) { await tx.$queryRaw`SELECT id FROM suppliers WHERE id = ${id} FOR UPDATE`; }
async function audit(tx: Tx, actorId: string, action: string, id: number, correlationId: string, beforeData: Prisma.InputJsonValue | null, afterData: Prisma.InputJsonValue) { await tx.tenantAuditEvent.create({ data: { actorId, action, entityType: "supplier", entityId: String(id), correlationId, beforeData: beforeData ?? undefined, afterData } }); }
async function recordAudit(db: Awaited<ReturnType<typeof tenantDb>>, actorId: string, action: string, id: number, correlationId: string, afterData: Prisma.InputJsonValue) { await db.tenantAuditEvent.create({ data: { actorId, action, entityType: "supplier", entityId: String(id), correlationId, afterData } }); }
function conflict() { const error = new Error("O fornecedor foi alterado por outro usuário."); Object.assign(error, { code: "SUPPLIER_CONFLICT" }); return error; }
function later(a?: Date | null, b?: Date | null) { if (!a) return b || null; if (!b) return a; return a > b ? a : b; }
function failure(error: unknown) { if (error instanceof SupplierInputError) return Response.json({ error: error.message }, { status: 400, headers: NO_STORE }); if (error instanceof PosHttpError) return Response.json({ error: error.message.replaceAll("PDV", "módulo de fornecedores") }, { status: error.status, headers: NO_STORE }); if (error instanceof LicenseDeniedError) return Response.json({ error: error.message }, { status: error.status, headers: NO_STORE }); if (error && typeof error === "object" && "code" in error && error.code === "P2002") return Response.json({ error: "Já existe um fornecedor com este CPF ou CNPJ, ou já há um registro principal ativo." }, { status: 409, headers: NO_STORE }); if (error && typeof error === "object" && "code" in error && ["P2034", "SUPPLIER_CONFLICT"].includes(String(error.code))) return Response.json({ error: "O fornecedor foi alterado por outro usuário. Atualize os dados e tente novamente." }, { status: 409, headers: NO_STORE }); if (error instanceof AuthError) return authErrorResponse(error); console.error("supplier detail request failed", error instanceof Error ? error.name : "unknown"); return Response.json({ error: "Não foi possível operar o fornecedor." }, { status: 500, headers: NO_STORE }); }
