import { currentOrganization, tenantDb } from "@/db";
import type { Prisma } from "@/generated/tenant/client";
import { AuthError, authErrorResponse } from "@/lib/auth";
import { assertSameOrigin } from "@/lib/erp/customer-input";
import { assertTenantPermission } from "@/lib/erp/permissions";
import { assertTenantWriteAccess } from "@/lib/tenant-access";
import { createPosT2BoundaryIdempotencyKey, toPosT2BoundaryIdempotencyKey, writePosT2WebhookBoundary } from "@/lib/erp/pos-t2-boundary";
import { IntegrationError, objectValue } from "@/lib/integrations/core";
import { privateJson, readIntegrationJson } from "@/lib/integrations/http";
import { deliverWebhook, serializeEndpoint, storeWebhookSecret, validateEndpointInput, webhookSecret } from "@/lib/integrations/webhooks";
import { unexpectedErrorResponse } from "@/lib/http-security";
type Context = { params: Promise<{ id: string }> };
async function context() { const organization = await currentOrganization(), access = await assertTenantPermission(organization.id, "integrations.write"); await assertTenantWriteAccess(organization.id); return { access, db: await tenantDb(organization.id) }; }
export async function PUT(request: Request, route: Context) { try { assertSameOrigin(request); const ctx = await context(), { id } = await route.params, body = await readIntegrationJson(request), input = await validateEndpointInput(body, true); const endpoint = await ctx.db.$transaction(async tx => { const before = await currentEndpoint(tx, id); const result = await writePosT2WebhookBoundary(tx, { action: "update", logicalId: before.logicalId, expectedVersion: before.version, expectedConfigHash: before.configHash, projection: { apiVersion: input.apiVersion, deliveryUrl: input.deliveryUrl, name: input.name, secretCipher: before.secretCipher, secretPreview: before.secretPreview, status: input.status as "active" | "paused" | "disabled", topic: before.topic }, actorUserId: ctx.access.user.id, idempotencyKey: boundaryKey(body) }); const saved = await tx.integrationWebhookEndpoint.findUniqueOrThrow({ where: { id: result.endpointId } }); await tx.integrationAuditLog.create({ data: { userId: ctx.access.user.id, action: "update", targetType: "webhook", targetId: saved.id, beforeData: serializeEndpoint(before), afterData: serializeEndpoint(saved) } }); return saved; }, { isolationLevel: "Serializable", maxWait: 10_000, timeout: 30_000 }); return privateJson({ endpoint: serializeEndpoint(endpoint) }); } catch (error) { return fail(error); } }
export async function DELETE(request: Request, route: Context) { try { assertSameOrigin(request); const ctx = await context(), { id } = await route.params, body = await optionalBody(request); await ctx.db.$transaction(async tx => { const before = await currentEndpoint(tx, id); const result = await writePosT2WebhookBoundary(tx, { action: "revoke", logicalId: before.logicalId, expectedVersion: before.version, expectedConfigHash: before.configHash, projection: { apiVersion: before.apiVersion, deliveryUrl: before.deliveryUrl, name: before.name, secretCipher: before.secretCipher, secretPreview: before.secretPreview, status: "disabled", topic: before.topic }, actorUserId: ctx.access.user.id, idempotencyKey: boundaryKey(body) }); await tx.integrationAuditLog.create({ data: { userId: ctx.access.user.id, action: "revoke", targetType: "webhook", targetId: result.endpointId, beforeData: serializeEndpoint(before), afterData: { logicalId: result.logicalId, version: result.version, status: result.status } } }); }, { isolationLevel: "Serializable", maxWait: 10_000, timeout: 30_000 }); return Response.json({ ok: true }); } catch (error) { return fail(error); } }
export async function POST(request: Request, route: Context) { try { assertSameOrigin(request); const ctx = await context(), { id } = await route.params, body = await readIntegrationJson(request), endpoint = await ctx.db.integrationWebhookEndpoint.findFirst({ where: { id, supersededAt: null } }); if (!endpoint) throw new IntegrationError("Webhook não encontrado ou versão superada.", 404); if (body.action === "rotate_secret") { if (body.confirm !== true) throw new IntegrationError("Confirme explicitamente a rotação do segredo.", 422); const secret = webhookSecret(), stored = storeWebhookSecret(secret), updated = await ctx.db.$transaction(async tx => { const before = await currentEndpoint(tx, id); const result = await writePosT2WebhookBoundary(tx, { action: "rotate", logicalId: before.logicalId, expectedVersion: before.version, expectedConfigHash: before.configHash, projection: { apiVersion: before.apiVersion, deliveryUrl: before.deliveryUrl, name: before.name, ...stored, status: before.status as "active" | "paused" | "disabled", topic: before.topic }, actorUserId: ctx.access.user.id, idempotencyKey: boundaryKey(body) }); const saved = await tx.integrationWebhookEndpoint.findUniqueOrThrow({ where: { id: result.endpointId } }); await tx.integrationAuditLog.create({ data: { userId: ctx.access.user.id, action: "rotate_secret", targetType: "webhook", targetId: saved.id, beforeData: { secretPreview: before.secretPreview }, afterData: { secretPreview: saved.secretPreview, version: saved.version } } }); return saved; }, { isolationLevel: "Serializable", maxWait: 10_000, timeout: 30_000 }); return privateJson({ endpoint: serializeEndpoint(updated), secret }); } if (body.action !== "test") throw new IntegrationError("Ação inválida."); const delivery = await ctx.db.integrationWebhookDelivery.create({ data: { endpointId: id, eventId: crypto.randomUUID(), topic: endpoint.topic, payload: { test: true, occurred_at: new Date().toISOString() } } }); return privateJson({ delivery: await deliverWebhook(ctx.db, delivery.id) }); } catch (error) { return fail(error); } }
async function currentEndpoint(tx: Prisma.TransactionClient, id: string) { const endpoint = await tx.integrationWebhookEndpoint.findFirst({ where: { id, supersededAt: null } }); if (!endpoint) throw new IntegrationError("Webhook não encontrado ou versão superada.", 404); return endpoint; }
async function optionalBody(request: Request) {
  const length = request.headers.get("content-length");
  if (length === "0" || (!request.body && length === null)) return {};
  return objectValue(await readIntegrationJson(request));
}
function boundaryKey(body: Record<string, unknown>) { const value = String(body.idempotency_key || body.idempotencyKey || ""); return value ? toPosT2BoundaryIdempotencyKey(value) : createPosT2BoundaryIdempotencyKey(); }
function fail(error: unknown) { if (error instanceof IntegrationError) return privateJson({ error: error.message }, { status: error.status }); if (error instanceof AuthError) return authErrorResponse(error); return unexpectedErrorResponse("erp.webhook",error); }
