import test from "node:test";
import assert from "node:assert/strict";
import {billingList,detailPayload,displayMoney,safePaymentUrl,visibleLicenseResources,publicPortalData} from "../lib/billing/portal-data";
test("fiscal documents and paginated collections preserve records",()=>{assert.deepEqual(billingList({documents:[{id:1}]}),[{id:1}]);assert.deepEqual(billingList({items:[]}),[]);assert.throws(()=>billingList({error:"offline"}));});
test("ticket detail preserves envelope messages and usable token",()=>{assert.deepEqual(detailPayload({ticket:{token:"abc",titulo:"Ajuda"},messages:[{id:4}]},"ticket").messages,[{id:4}]);assert.equal(detailPayload({ticket:{token:"abc"}},"ticket").token,"abc");});
test("zero is money and unknown is not zero",()=>{assert.match(displayMoney(0),/0,00/);for(const v of [null,undefined,"",false,"invalid"])assert.equal(displayMoney(v),"—");});
test("checkout blocks executable and credential-bearing URLs",()=>{for(const v of ['javascript:alert(1)','http://example.com','https://user:pass@example.com',null])assert.equal(safePaymentUrl(v),null);assert.equal(safePaymentUrl('https://checkout.example.com/pay'),'https://checkout.example.com/pay');});
test("retail license excludes services, marketplaces and zero entitlements",()=>{const rows=visibleLicenseResources([{codigo:"nalven_servicos_recorrencia",habilitado:true},{codigo:"nalven_canais_digitais",habilitado:true,limite:1},{codigo:"nalven_api_integracao",habilitado:true,limite:null},{codigo:"nalven_catalogo",nome:"Produtos e serviços",habilitado:true,limite:null},{codigo:"zero",habilitado:true,limite:0}],false,false);assert.deepEqual(rows.map(r=>r.codigo),["nalven_api_integracao","nalven_catalogo"]);assert.equal(rows[1].nome,"Produtos");});
test("portal redaction keeps scoped document tokens but removes license keys and prefixes",()=>{assert.deepEqual(publicPortalData({ticket:{token:"scoped-document"},license:{chave:"secret",chave_prefix:"abc",key:"one-time-secret",licenseKey:"secret",licenseSecret:"secret",key_prefix:"abc",authorization:"private"},customer:{responsavel_cpf:"private"},installation:{metadata:{credential_id:"private"}},resources:[{codigo:"public-code",limite:0}]}),{ticket:{token:"scoped-document"},license:{},customer:{},installation:{},resources:[{codigo:"public-code",limite:0}]});});
