"use client";

import { tenantDateTimeFormatter } from "@/lib/client-timezone";
import Link from "next/link";
import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ErpIcon } from "@/components/erp/erp-icon";
import { ErpModal } from "@/components/erp/modal-portal";
import styles from "./user-access-center.module.css";

const dateTime = tenantDateTimeFormatter({ dateStyle: "short", timeStyle: "short" });
const date = tenantDateTimeFormatter({ dateStyle: "short" });
const statusLabels: Record<string, string> = { active: "Ativo", disabled: "Bloqueado", expired: "Expirado", pending: "Pendente", accepted: "Aceito", revoked: "Revogado" };
const actionLabels: Record<string, string> = {
  "organization_invite.created": "Convite emitido", "organization_invite.rotated": "Link de convite renovado", "organization_invite.revoked": "Convite revogado", "organization_invite.accepted": "Convite aceito",
  "tenant_role.created": "Perfil criado", "tenant_role.updated": "Permissões alteradas", "tenant_role.status_changed": "Status do perfil alterado", "membership.updated": "Acesso de usuário alterado",
  "membership.bulk_updated": "Ação aplicada em lote", "membership.access_reviewed": "Acesso revisado", "membership.sessions_revoked": "Sessões encerradas",
};

type BranchGrant = { branchId: number; canSell: boolean; canManageStock: boolean; canIssueFiscal: boolean; primary: boolean };
type Profile = { id: number; jobTitle: string | null; department: string | null; phone: string | null; status: string; accessExpiresAt: string | null; lastAccessReviewAt: string | null; accessReviewedBy: string | null; activeBranchId: number | null; lastSyncedAt: string; branchAccesses: BranchGrant[] };
type Member = {
  id: string; roleKey: string; roleName: string; status: string; accessState: string; createdAt: string; profile: Profile | null;
  user: { id: string; name: string; email: string; status: string; emailVerifiedAt: string | null; lastLoginAt: string | null; createdAt: string; activeSessions: number; sessions: Array<{ id: string; createdAt: string; expiresAt: string; device: string; ip: string }> };
  security: { stale: boolean; reviewDue: boolean; issues: string[]; score: number };
};
type Role = { id: number; key: string; name: string; description: string | null; permissions: string[]; system: boolean; active: boolean; _count: { members: number } };
type Invite = { id: string; email: string; name: string | null; roleKey: string; status: string; expiresAt: string; acceptedAt: string | null; revokedAt: string | null; createdAt: string; invitedBy: { name: string; email: string } };
type Data = {
  members: Member[]; roles: Role[]; invites: Invite[]; branches: Array<{ id: number; code: string; name: string; primary: boolean }>;
  activity: Array<{ id: string; actorId: string | null; action: string; entityType: string; entityId: string | null; correlationId: string | null; afterData: unknown; createdAt: string; actor: { name: string; email: string } | null }>;
  permissionResources: Array<{ key: string; label: string }>; capabilities: { canWrite: boolean }; generatedAt: string;
  summary: { active: number; disabled: number; expired: number; pending: number; roles: number; sessions: number; stale: number; reviewDue: number; branchCoverage: number };
};
type View = "overview" | "members" | "invites" | "roles" | "activity";

export function UserAccessCenter({ organizationId }: { organizationId?: string } = {}) {
  const endpoint = organizationId ? `/api/admin/organizations/${encodeURIComponent(organizationId)}/users` : "/api/erp/users";
  const [data, setData] = useState<Data | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [view, setView] = useState<View>("overview"), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [role, setRole] = useState(""), [attention, setAttention] = useState("");
  const [selected, setSelected] = useState<string[]>([]), [selectedInvites, setSelectedInvites] = useState<string[]>([]), [memberOpen, setMemberOpen] = useState<Member | null>(null), [inviteOpen, setInviteOpen] = useState(false), [roleOpen, setRoleOpen] = useState<Role | null | undefined>(undefined), [oneTimeUrl, setOneTimeUrl] = useState(""), [copied, setCopied] = useState(false);

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await fetch(endpoint, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error || "Não foi possível carregar usuários e acessos."); setData(body); setSelected(current => current.filter(id => body.members.some((item: Member) => item.id === id))); setSelectedInvites(current => current.filter(id => body.invites.some((item: Invite) => item.id === id && item.status === "pending"))); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar usuários e acessos."); }
    finally { setLoading(false); }
  }, [endpoint]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const command = useCallback(async (payload: Record<string, unknown>, success: string) => {
    setBusy(true); setError(""); setNotice("");
    try { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }), body = await response.json(); if (!response.ok) throw new Error(body.error || "A operação não pôde ser concluída."); setNotice(success); await load(); return body as Record<string, unknown>; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "A operação não pôde ser concluída."); return null; }
    finally { setBusy(false); }
  }, [load, endpoint]);

  const filteredMembers = useMemo(() => {
    const term = search.trim().toLocaleLowerCase("pt-BR");
    return (data?.members || []).filter(member => {
      const text = [member.user.name, member.user.email, member.roleName, member.profile?.department, member.profile?.jobTitle].join(" ").toLocaleLowerCase("pt-BR");
      return (!term || text.includes(term)) && (!status || member.accessState === status) && (!role || member.roleKey === role) && (!attention || (attention === "stale" ? member.security.stale : attention === "review" ? member.security.reviewDue : attention === "branch" ? member.roleKey !== "owner" && !member.profile?.branchAccesses.length : member.security.issues.length > 0));
    });
  }, [data, search, status, role, attention]);
  const selectableMembers = filteredMembers.filter(item => item.roleKey !== "owner"), allSelected = selectableMembers.length > 0 && selectableMembers.every(item => selected.includes(item.id));

  function focusMembers(kind: string) { setAttention(kind); setStatus(""); setSearch(""); setRole(""); setView("members"); }
  async function bulk(payload: Record<string, unknown>, message: string) {
    if (!selected.length) return;
    if (payload.status === "disabled" || payload.revokeSessions === true) {
      const action = payload.status === "disabled" ? `Bloquear ${selected.length} acesso(s) nesta organização e encerrar as sessões dessas contas?` : `Encerrar as sessões de ${selected.length} conta(s)?`;
      if (!window.confirm(`${action} Todas as sessões dessas contas serão encerradas, inclusive em outras organizações. Os vínculos com outras organizações não serão bloqueados.`)) return;
    }
    if (await command({ action: "member.bulk_update", membershipIds: selected, ...payload }, message)) setSelected([]);
  }
  async function invite(payload: Record<string, unknown>) { const result = await command({ action: "invite.create", ...payload }, "Convite criado. Copie o link e envie por um canal seguro."); if (result) { setInviteOpen(false); setOneTimeUrl(String(result.acceptanceUrl)); setView("invites"); } }
  async function rotate(id: string) { const result = await command({ action: "invite.rotate", inviteId: id }, "O link anterior foi invalidado e um novo link foi emitido."); if (result) setOneTimeUrl(String(result.acceptanceUrl)); }
  async function copyLink() { try { await navigator.clipboard.writeText(oneTimeUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setError("O navegador bloqueou a cópia. Selecione o link manualmente."); } }
  function exportCsv() { const link = document.createElement("a"); link.href = `${endpoint}?format=csv`; link.download = "usuarios-acessos.csv"; link.click(); }

  if (!data && loading) return <Loading />;
  if (!data) return <Fatal message={error} retry={() => void load()} />;
  const coverage = data.members.length ? Math.round(data.summary.branchCoverage / data.members.length * 100) : 100;
  const securityScore = data.members.length ? Math.round(data.members.reduce((sum, item) => sum + item.security.score, 0) / data.members.length) : 100;

  return <div className={styles.workspace}>
    <header className={styles.hero}>
      <div><span>IDENTIDADE E ACESSO</span>{organizationId ? <h2>Usuários desta organização</h2> : <h1>Central de usuários</h1>}<p>Administre pessoas, perfis, permissões, filiais, sessões e revisões de acesso com rastreabilidade de ponta a ponta.</p>{!organizationId && <nav aria-label="Atalhos de segurança"><Link href="/erp/empresas-filiais"><ErpIcon name="branches" />Filiais</Link><Link href="/erp/atividades-auditoria"><ErpIcon name="activities" />Auditoria</Link><Link href="/erp/configuracoes"><ErpIcon name="settings" />Políticas</Link></nav>}</div>
      <section><small>POSTURA DE ACESSO</small><strong>{securityScore}/100</strong><span><i className={securityScore >= 85 ? styles.goodDot : securityScore >= 65 ? styles.warnDot : styles.badDot} />{securityScore >= 85 ? "Ambiente saudável" : securityScore >= 65 ? "Revisões recomendadas" : "Atenção prioritária"}</span><b>Atualizado {dateTime.format(new Date(data.generatedAt))}</b></section>
    </header>
    {oneTimeUrl && <section className={styles.secureLink} role="status"><div><span>LINK DE USO ÚNICO</span><strong>Compartilhe por um canal seguro</strong><small>O token não poderá ser recuperado depois que este aviso for fechado.</small></div><code>{oneTimeUrl}</code><button onClick={() => void copyLink()}>{copied ? "Copiado ✓" : "Copiar link"}</button><button onClick={() => setOneTimeUrl("")} aria-label="Fechar link">×</button></section>}
    {notice && <div className={styles.notice} role="status"><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Fechar aviso">×</button></div>}
    {error && <div className={styles.error} role="alert"><span>{error}</span><button onClick={() => setError("")} aria-label="Fechar erro">×</button></div>}
    <section className={styles.metrics} aria-label="Indicadores de acesso">
      <Metric icon="✓" label="Acessos ativos" value={String(data.summary.active)} note={`${data.summary.disabled + data.summary.expired} restritos`} tone="good" />
      <Metric icon="◎" label="Sessões abertas" value={String(data.summary.sessions)} note="Dispositivos conectados" />
      <Metric icon="✉" label="Convites pendentes" value={String(data.summary.pending)} note="Aguardando aceite" tone={data.summary.pending ? "warn" : "good"} />
      <Metric icon="◫" label="Perfis ativos" value={String(data.summary.roles)} note="Matrizes de permissão" />
      <Metric icon="!" label="Revisões vencidas" value={String(data.summary.reviewDue)} note="Ciclo recomendado: 90 dias" tone={data.summary.reviewDue ? "warn" : "good"} />
      <Metric icon="⌁" label="Cobertura por filial" value={`${coverage}%`} note="Usuários com escopo" tone={coverage < 100 ? "warn" : "good"} />
    </section>
    <section className={styles.control}><div className={styles.tabs} role="tablist" aria-label="Visões da central">{([['overview','Visão executiva'],['members','Equipe'],['invites','Convites'],['roles','Perfis'],['activity','Atividade']] as Array<[View,string]>).map(([key, label]) => <button key={key} role="tab" aria-selected={view === key} onClick={() => setView(key)}>{label}{key === "invites" && data.summary.pending > 0 && <b>{data.summary.pending}</b>}</button>)}</div><div className={styles.topActions}><button onClick={exportCsv}>Exportar CSV</button>{data.capabilities.canWrite && <button className={styles.primary} onClick={() => setInviteOpen(true)}>+ Convidar usuário</button>}</div></section>

    {view === "overview" && <Overview data={data} securityScore={securityScore} coverage={coverage} focus={focusMembers} openMember={setMemberOpen} setView={setView} />}
    {view === "members" && <>
      <section className={styles.filters}><label className={styles.search}>Buscar pessoa, e-mail, cargo ou área<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Ex.: financeiro, Ana…" /></label><label>Status<select value={status} onChange={event => setStatus(event.target.value)}><option value="">Todos</option><option value="active">Ativos</option><option value="disabled">Bloqueados</option><option value="expired">Expirados</option></select></label><label>Perfil<select value={role} onChange={event => setRole(event.target.value)}><option value="">Todos</option>{data.roles.map(item => <option value={item.key} key={item.id}>{item.name}</option>)}</select></label><label>Atenção<select value={attention} onChange={event => setAttention(event.target.value)}><option value="">Todos</option><option value="issues">Com pendências</option><option value="review">Revisão vencida</option><option value="stale">Acesso inativo</option><option value="branch">Sem filial</option></select></label><button onClick={() => { setSearch(""); setStatus(""); setRole(""); setAttention(""); }}>Limpar</button></section>
      {selected.length > 0 && <section className={styles.batch}><strong>{selected.length} usuário(s) selecionado(s)</strong><button disabled={busy} onClick={() => void bulk({ status: "active" }, "Acessos ativados.")}>Ativar</button><button disabled={busy} onClick={() => void bulk({ status: "disabled" }, "Acessos bloqueados e sessões encerradas.")}>Bloquear</button><button disabled={busy} onClick={() => void bulk({ revokeSessions: true }, "Sessões ativas encerradas.")}>Encerrar sessões</button><button onClick={() => setSelected([])}>Limpar</button></section>}
      <section className={styles.tablePanel}><header><div><span>DIRETÓRIO DA ORGANIZAÇÃO</span><h2>Equipe e acessos</h2></div><small>{filteredMembers.length} de {data.members.length} usuário(s)</small></header><div className={styles.tableScroll}><table><thead><tr><th><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : selectableMembers.map(item => item.id))} aria-label="Selecionar usuários exibidos" /></th><th>Usuário</th><th>Perfil e função</th><th>Filiais</th><th>Último acesso</th><th>Segurança</th><th>Status</th><th><span className={styles.srOnly}>Ações</span></th></tr></thead><tbody>{filteredMembers.map(member => <MemberRow key={member.id} member={member} branches={data.branches} selected={selected.includes(member.id)} toggle={() => setSelected(current => current.includes(member.id) ? current.filter(id => id !== member.id) : [...current, member.id])} open={() => setMemberOpen(member)} />)}</tbody></table></div>{!filteredMembers.length && <Empty title="Nenhum usuário neste recorte" text="Ajuste os filtros ou convide uma nova pessoa para a organização." />}</section>
    </>}
    {view === "invites" && <Invites data={data} selected={selectedInvites} setSelected={setSelectedInvites} busy={busy} rotate={rotate} revoke={async id => { await command({ action: "invite.revoke", inviteId: id }, "Convite revogado."); }} bulkRevoke={async () => { if (!window.confirm(`Revogar ${selectedInvites.length} convite(s)?`)) return; if (await command({ action: "invite.bulk_revoke", inviteIds: selectedInvites }, "Convites pendentes revogados.")) setSelectedInvites([]); }} create={() => setInviteOpen(true)} />}
    {view === "roles" && <Roles data={data} edit={role => setRoleOpen(role)} create={() => setRoleOpen(null)} />}
    {view === "activity" && <Activity events={data.activity} embedded={!!organizationId} />}

    {memberOpen && <MemberDialog member={memberOpen} data={data} busy={busy} close={() => setMemberOpen(null)} save={async payload => { if (await command({ action: "member.update", membershipId: memberOpen.id, ...payload }, "Perfil, validade e escopos do usuário foram atualizados.")) setMemberOpen(null); }} review={async () => { if (await command({ action: "member.review", membershipId: memberOpen.id }, "Revisão de acesso registrada.")) setMemberOpen(null); }} revokeSessions={async () => { if (!window.confirm(`Encerrar todas as sessões ativas de ${memberOpen.user.name}? Isso desconecta a conta também de outras organizações, sem bloquear seus vínculos.`)) return; if (await command({ action: "member.sessions_revoke", membershipId: memberOpen.id }, "Sessões do usuário encerradas.")) setMemberOpen(null); }} />}
    {inviteOpen && <InviteDialog roles={data.roles.filter(item => item.active && item.key !== "owner")} busy={busy} close={() => setInviteOpen(false)} submit={invite} />}
    {roleOpen !== undefined && <RoleDialog role={roleOpen || undefined} resources={data.permissionResources} busy={busy} close={() => setRoleOpen(undefined)} submit={async payload => { const result = await command({ action: roleOpen ? "role.update" : "role.create", ...(roleOpen ? { roleId: roleOpen.id } : {}), ...payload }, roleOpen ? "Perfil e permissões atualizados." : "Novo perfil de acesso criado."); if (result) setRoleOpen(undefined); }} />}
  </div>;
}

function Metric({ icon, label, value, note, tone = "" }: { icon: string; label: string; value: string; note: string; tone?: string }) { return <article className={tone ? styles[tone] : ""}><i>{icon}</i><span><small>{label}</small><strong>{value}</strong><b>{note}</b></span></article>; }

function Overview({ data, securityScore, coverage, focus, openMember, setView }: { data: Data; securityScore: number; coverage: number; focus: (kind: string) => void; openMember: (member: Member) => void; setView: (view: View) => void }) {
  const attention = [
    { key: "review", label: "Revisões vencidas", value: data.summary.reviewDue, text: "Acessos sem recertificação há 90 dias" },
    { key: "stale", label: "Baixa atividade", value: data.summary.stale, text: "Sem login há mais de 45 dias" },
    { key: "branch", label: "Sem escopo de filial", value: data.members.length - data.summary.branchCoverage, text: "Usuários operacionais sem unidade" },
    { key: "issues", label: "Acessos expirados", value: data.summary.expired, text: "Validade temporária encerrada" },
  ];
  return <section className={styles.overview}>
    <section className={styles.panel}><header><div><span>GOVERNANÇA CONTÍNUA</span><h2>Pendências de acesso</h2></div><b>{attention.reduce((sum, item) => sum + item.value, 0)} sinais</b></header><div className={styles.attention}>{attention.map(item => <button key={item.key} onClick={() => focus(item.key)}><i className={item.value ? styles.warnDot : styles.goodDot} /><span><strong>{item.label}</strong><small>{item.text}</small></span><b>{item.value}</b><em>Revisar →</em></button>)}</div></section>
    <section className={styles.posture}><span>POSTURA DE SEGURANÇA</span><h2>Controles essenciais</h2><div><Score label="Saúde média" value={securityScore} /><Score label="Cobertura de filial" value={coverage} /><Score label="Acessos ativos" value={Math.round(data.summary.active / Math.max(data.members.length, 1) * 100)} /></div><p>As permissões são avaliadas em tempo real. Bloqueios e expirações passam a valer em todos os módulos do ERP.</p></section>
    <section className={styles.panel}><header><div><span>ACESSOS RECENTES</span><h2>Última atividade da equipe</h2></div><button onClick={() => setView("members")}>Ver equipe</button></header><div className={styles.recent}>{[...data.members].sort((a,b) => new Date(b.user.lastLoginAt || 0).getTime() - new Date(a.user.lastLoginAt || 0).getTime()).slice(0,5).map(member => <button key={member.id} onClick={() => openMember(member)}><Avatar name={member.user.name} /><span><strong>{member.user.name}</strong><small>{member.roleName} · {member.user.lastLoginAt ? relative(member.user.lastLoginAt) : "Nunca acessou"}</small></span><Status value={member.accessState} /></button>)}</div></section>
    <section className={styles.panel}><header><div><span>DISTRIBUIÇÃO DE PRIVILÉGIOS</span><h2>Usuários por perfil</h2></div><button onClick={() => setView("roles")}>Ver perfis</button></header><div className={styles.roleBreakdown}>{data.roles.filter(item => item._count.members > 0).map(item => <div key={item.id}><span><strong>{item.name}</strong><small>{item.permissions.includes("*") ? "Acesso integral" : `${item.permissions.length} permissões`}</small></span><i><em style={{ width: `${item._count.members / Math.max(data.members.length,1) * 100}%` }} /></i><b>{item._count.members}</b></div>)}</div></section>
  </section>;
}
function Score({ label, value }: { label: string; value: number }) { return <section><i style={{ background: `conic-gradient(#53d194 ${value * 3.6}deg,rgba(255,255,255,.14) 0)` }}><b>{value}%</b></i><span>{label}</span></section>; }

function MemberRow({ member, branches, selected, toggle, open }: { member: Member; branches: Data["branches"]; selected: boolean; toggle: () => void; open: () => void }) {
  const names = (member.profile?.branchAccesses || []).map(grant => branches.find(item => item.id === grant.branchId)?.name).filter(Boolean);
  return <tr><td>{member.roleKey !== "owner" && <input type="checkbox" checked={selected} onChange={toggle} aria-label={`Selecionar ${member.user.name}`} />}</td><td><button className={styles.person} onClick={open}><Avatar name={member.user.name} /><span><strong>{member.user.name}</strong><small>{member.user.email}</small></span></button></td><td><strong>{member.roleName}</strong><small>{member.profile?.jobTitle || member.profile?.department || "Função não informada"}</small></td><td><strong>{member.roleKey === "owner" ? "Todas" : names.slice(0,2).join(", ") || "Nenhuma"}</strong><small>{member.roleKey !== "owner" && names.length > 2 ? `+${names.length - 2} filial(is)` : member.profile?.branchAccesses.some(item => item.canSell) ? "Venda autorizada" : "Escopo administrativo"}</small></td><td><strong>{member.user.lastLoginAt ? relative(member.user.lastLoginAt) : "Nunca"}</strong><small>{member.user.activeSessions} sessão(ões) ativa(s)</small></td><td><div className={styles.health}><i style={{ background: `conic-gradient(currentColor ${member.security.score * 3.6}deg,#e5ece9 0)` }} /><span><strong>{member.security.score}/100</strong><small>{member.security.issues[0] || "Sem pendências"}</small></span></div></td><td><Status value={member.accessState} /></td><td><button className={styles.actionButton} onClick={open} aria-label={`Gerenciar ${member.user.name}`}>•••</button></td></tr>;
}

function Invites({ data, selected, setSelected, busy, rotate, revoke, bulkRevoke, create }: { data: Data; selected: string[]; setSelected: (value: string[] | ((current: string[]) => string[])) => void; busy: boolean; rotate: (id: string) => Promise<void>; revoke: (id: string) => Promise<void>; bulkRevoke: () => Promise<void>; create: () => void }) {
  const roleName = (key: string) => data.roles.find(item => item.key === key)?.name || key, all = data.invites.filter(item => item.status === "pending").map(item => item.id);
  return <section className={styles.inviteView}><section className={styles.guide}><div><span>ONBOARDING SEGURO</span><h2>Convites com token de uso único</h2><p>O banco armazena somente o hash. Renovar um convite invalida o link anterior, e o aceite cria o perfil operacional no tenant.</p></div><ol><li><b>1</b><span><strong>Defina o perfil</strong><small>Privilégio mínimo para a função</small></span></li><li><b>2</b><span><strong>Envie o link</strong><small>Use um canal verificado</small></span></li><li><b>3</b><span><strong>Revise o acesso</strong><small>Recertifique a cada 90 dias</small></span></li></ol></section><section className={styles.tablePanel}><header><div><span>CICLO DE CONVITES</span><h2>Histórico de convites</h2></div><div>{selected.length > 0 && <button disabled={busy} onClick={() => void bulkRevoke()}>Revogar {selected.length}</button>}<button className={styles.primary} onClick={create}>+ Novo convite</button></div></header><div className={styles.inviteList}>{data.invites.map(invite => <article key={invite.id}><input type="checkbox" disabled={invite.status !== "pending"} checked={selected.includes(invite.id)} onChange={() => setSelected(current => current.includes(invite.id) ? current.filter(id => id !== invite.id) : [...current, invite.id])} aria-label={`Selecionar convite de ${invite.email}`} /><span className={styles.mailIcon}>@</span><div><strong>{invite.name || invite.email}</strong><small>{invite.email} · {roleName(invite.roleKey)}</small><em>Emitido por {invite.invitedBy.name} em {dateTime.format(new Date(invite.createdAt))}</em></div><Status value={invite.status} /><time>{invite.status === "pending" ? `Expira ${relative(invite.expiresAt)}` : date.format(new Date(invite.acceptedAt || invite.revokedAt || invite.expiresAt))}</time>{invite.status === "pending" && <details className={styles.actions}><summary aria-label="Ações do convite">•••</summary><div><button disabled={busy} onClick={() => void rotate(invite.id)}>Gerar novo link</button><button className={styles.dangerText} disabled={busy} onClick={() => void revoke(invite.id)}>Revogar convite</button></div></details>}</article>)}</div>{!data.invites.length && <Empty title="Nenhum convite emitido" text="Convide uma pessoa e escolha o perfil adequado para iniciar o onboarding." />}<footer><label><input type="checkbox" checked={all.length > 0 && all.every(id => selected.includes(id))} onChange={() => setSelected(all.length > 0 && all.every(id => selected.includes(id)) ? [] : all)} />Selecionar todos os pendentes</label><span>{data.summary.pending} pendente(s)</span></footer></section></section>;
}

function Roles({ data, edit, create }: { data: Data; edit: (role: Role) => void; create: () => void }) {
  return <section className={styles.rolesView}><section className={styles.rolesHeader}><div><span>MATRIZ RBAC</span><h2>Perfis e permissões</h2><p>Combine consulta e alteração por recurso. A escrita já concede a leitura do mesmo módulo.</p></div>{data.capabilities.canWrite && <button className={styles.primary} onClick={create}>+ Novo perfil</button>}</section><div className={styles.roleGrid}>{data.roles.map(role => <article key={role.id} className={!role.active ? styles.inactive : ""}><header><span>{role.system ? "PERFIL DO SISTEMA" : "PERSONALIZADO"}</span><Status value={role.active ? "active" : "disabled"} /></header><h2>{role.name}</h2><p>{role.description || "Sem descrição operacional."}</p><dl><div><dt>Usuários</dt><dd>{role._count.members}</dd></div><div><dt>Permissões</dt><dd>{role.permissions.includes("*") ? "Todas" : role.permissions.length}</dd></div><div><dt>Escrita</dt><dd>{role.permissions.includes("*") ? "Integral" : role.permissions.filter(item => item.endsWith(".write")).length}</dd></div></dl><footer><small>{role.key}</small>{role.key === "owner" ? <span>Protegido</span> : data.capabilities.canWrite && <button onClick={() => edit(role)}>Configurar</button>}</footer></article>)}</div></section>;
}
function Activity({ events, embedded }: { events: Data["activity"]; embedded: boolean }) { return <section className={styles.activityView}><section className={styles.panel}><header><div><span>TRILHA IMUTÁVEL</span><h2>Atividade de identidade e acesso</h2></div><b>{events.length} eventos recentes</b></header><div className={styles.timeline}>{events.map(event => <article key={event.id}><i /><time>{dateTime.format(new Date(event.createdAt))}</time><span><strong>{actionLabels[event.action] || event.action}</strong><small>{event.actor?.name || "Sistema"} · {event.entityType}{event.entityId ? ` #${event.entityId.slice(-8)}` : ""}</small></span>{event.correlationId && <code title={event.correlationId}>{event.correlationId.slice(0,8)}</code>}</article>)}{!events.length && <Empty title="Sem eventos de acesso" text="Alterações de usuários, perfis, convites e sessões aparecerão aqui." />}</div></section><aside><span>CONTROLES ATIVOS</span><h2>O que fica registrado</h2><ul><li>Emissão, renovação e revogação de convites</li><li>Alterações de perfil, status e filiais</li><li>Revisões periódicas de acesso</li><li>Encerramento administrativo de sessões</li><li>Correlação de cada operação sensível</li></ul>{!embedded && <Link href="/erp/atividades-auditoria">Abrir auditoria completa →</Link>}</aside></section>; }

function MemberDialog({ member, data, busy, close, save, review, revokeSessions }: { member: Member; data: Data; busy: boolean; close: () => void; save: (payload: Record<string, unknown>) => Promise<void>; review: () => Promise<void>; revokeSessions: () => Promise<void> }) {
  const owner = member.roleKey === "owner";
  const [tab, setTab] = useState<"profile" | "branches" | "security">("profile"), [roleKey, setRoleKey] = useState(member.roleKey), [status, setStatus] = useState(member.status), [jobTitle, setJobTitle] = useState(member.profile?.jobTitle || ""), [department, setDepartment] = useState(member.profile?.department || ""), [phone, setPhone] = useState(member.profile?.phone || ""), [accessExpiresAt, setAccessExpiresAt] = useState(member.profile?.accessExpiresAt ? localDate(member.profile.accessExpiresAt) : ""), [grants, setGrants] = useState<Record<number, BranchGrant>>(() => Object.fromEntries((member.profile?.branchAccesses || []).map(item => [item.branchId, item])));
  function toggleBranch(branchId: number) { setGrants(current => { const next = { ...current }; if (next[branchId]) { const wasPrimary = next[branchId].primary; delete next[branchId]; if (wasPrimary) { const first = Object.values(next)[0]; if (first) next[first.branchId] = { ...first, primary: true }; } } else { next[branchId] = { branchId, canSell: false, canManageStock: false, canIssueFiscal: false, primary: Object.keys(next).length === 0 }; } return next; }); }
  function changeGrant(branchId: number, key: keyof Omit<BranchGrant,"branchId">, value: boolean) { setGrants(current => { const next = { ...current }; if (key === "primary" && value) for (const item of Object.values(next)) next[item.branchId] = { ...item, primary: false }; next[branchId] = { ...next[branchId], [key]: value }; return next; }); }
  async function submit(event: FormEvent) {
    event.preventDefault();
    if (status === "disabled" && !window.confirm(`Salvar o acesso bloqueado de ${member.user.name} nesta organização? Todas as sessões da conta serão encerradas, inclusive em outras organizações. Os vínculos com outras organizações não serão bloqueados.`)) return;
    await save({ roleKey, status, jobTitle, department, phone, accessExpiresAt: accessExpiresAt ? new Date(`${accessExpiresAt}T23:59:59`).toISOString() : null, branchAccesses: Object.values(grants) });
  }
  return <ErpModal close={close} className={styles.modalLayer} label={`Gerenciar acesso de ${member.user.name}`}><form className={styles.memberDialog} onSubmit={submit}><header><div className={styles.dialogIdentity}><Avatar name={member.user.name} /><span><small>PERFIL DE ACESSO</small><h2>{member.user.name}</h2><p>{member.user.email}</p></span></div><Status value={member.accessState} /><button type="button" onClick={close} aria-label="Fechar">×</button></header><nav role="tablist"><button type="button" role="tab" aria-selected={tab === "profile"} onClick={() => setTab("profile")}>Perfil e validade</button><button type="button" role="tab" aria-selected={tab === "branches"} onClick={() => setTab("branches")}>Filiais e operações</button><button type="button" role="tab" aria-selected={tab === "security"} onClick={() => setTab("security")}>Segurança e sessões</button></nav><div className={styles.dialogBody}>
    {tab === "profile" && <section className={styles.profileFields}><label>Perfil de permissão<select value={roleKey} disabled={owner} onChange={event => setRoleKey(event.target.value)}>{data.roles.filter(item => item.active && (item.key !== "owner" || owner)).map(item => <option value={item.key} key={item.id}>{item.name}</option>)}</select></label><label>Status do acesso<select value={status} disabled={owner} onChange={event => setStatus(event.target.value)}><option value="active">Ativo</option><option value="disabled">Bloqueado</option></select></label><label>Cargo<input value={jobTitle} disabled={owner} onChange={event => setJobTitle(event.target.value)} maxLength={120} placeholder="Ex.: Analista financeiro" /></label><label>Departamento<input value={department} disabled={owner} onChange={event => setDepartment(event.target.value)} maxLength={120} placeholder="Ex.: Financeiro" /></label><label>Telefone<input value={phone} disabled={owner} onChange={event => setPhone(event.target.value)} maxLength={30} placeholder="(00) 00000-0000" /></label><label>Validade do acesso<input type="date" value={accessExpiresAt} disabled={owner} min={today()} onChange={event => setAccessExpiresAt(event.target.value)} /><small>Deixe vazio para acesso permanente.</small></label><div className={styles.identityFacts}><span><small>E-mail</small><strong>{member.user.emailVerifiedAt ? "Verificado" : "Pendente"}</strong></span><span><small>Membro desde</small><strong>{date.format(new Date(member.createdAt))}</strong></span><span><small>Última sincronização</small><strong>{member.profile ? relative(member.profile.lastSyncedAt) : "Pendente"}</strong></span></div></section>}
    {tab === "branches" && <section><p className={styles.help}>Defina em quais unidades a pessoa pode operar e quais capacidades locais estão liberadas. O perfil RBAC continua controlando o acesso ao módulo.</p><div className={styles.branchMatrix}><header><span>Filial</span><span>Principal</span><span>Vender</span><span>Estoque</span><span>Fiscal</span></header>{data.branches.map(branch => { const grant = grants[branch.id]; return <div key={branch.id}><label><input type="checkbox" checked={Boolean(grant)} disabled={owner} onChange={() => toggleBranch(branch.id)} /><span><strong>{branch.name}</strong><small>{branch.code}{branch.primary ? " · Matriz" : ""}</small></span></label>{(["primary","canSell","canManageStock","canIssueFiscal"] as const).map(key => <input key={key} type={key === "primary" ? "radio" : "checkbox"} name={key === "primary" ? "primaryBranch" : undefined} checked={owner ? true : Boolean(grant?.[key])} disabled={owner || !grant} onChange={event => changeGrant(branch.id, key, event.target.checked)} aria-label={`${key} em ${branch.name}`} />)}</div>})}</div>{!data.branches.length && <Empty title="Nenhuma filial ativa" text="Cadastre uma filial antes de definir o escopo operacional." />}</section>}
    {tab === "security" && <section className={styles.securityTab}><div className={styles.securitySummary}><ScoreCard label="Saúde do acesso" value={`${member.security.score}/100`} detail={member.security.issues.length ? `${member.security.issues.length} ponto(s) de atenção` : "Sem pendências"} /><ScoreCard label="Última revisão" value={member.profile?.lastAccessReviewAt ? relative(member.profile.lastAccessReviewAt) : "Nunca"} detail="Periodicidade recomendada: 90 dias" /><ScoreCard label="Sessões ativas" value={String(member.user.activeSessions)} detail={member.user.lastLoginAt ? `Último login ${relative(member.user.lastLoginAt)}` : "Usuário ainda não acessou"} /></div>{member.security.issues.length > 0 && <div className={styles.issueList}>{member.security.issues.map(issue => <span key={issue}>! {issue}</span>)}</div>}<section className={styles.sessionList}><header><h3>Dispositivos conectados</h3>{!owner && member.user.activeSessions > 0 && <button type="button" disabled={busy} onClick={() => void revokeSessions()}>Encerrar todas</button>}</header>{member.user.sessions.map(session => <article key={session.id}><i>◎</i><span><strong>{session.device}</strong><small>{session.ip} · iniciada {relative(session.createdAt)}</small></span><time>Expira {relative(session.expiresAt)}</time></article>)}{!member.user.sessions.length && <p>Nenhuma sessão ativa.</p>}</section>{!owner && <button className={styles.reviewButton} type="button" disabled={busy} onClick={() => void review()}>✓ Registrar revisão de acesso agora</button>}</section>}
  </div><footer><span>{owner ? "O proprietário possui acesso integral protegido." : "Alterações são registradas na trilha de auditoria."}</span><div><button type="button" onClick={close}>Cancelar</button>{!owner && <button className={styles.primary} disabled={busy}>{busy ? "Salvando…" : "Salvar acesso"}</button>}</div></footer></form></ErpModal>;
}

function InviteDialog({ roles, busy, close, submit }: { roles: Role[]; busy: boolean; close: () => void; submit: (payload: Record<string, unknown>) => Promise<void> }) { async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await submit(Object.fromEntries(new FormData(event.currentTarget))); } return <ErpModal close={close} className={styles.modalLayer} label="Convidar usuário"><form className={styles.smallDialog} onSubmit={save}><header><div><span>ONBOARDING SEGURO</span><h2>Convidar usuário</h2><p>Defina a identidade, o menor privilégio necessário e a validade do link.</p></div><button type="button" onClick={close} aria-label="Fechar">×</button></header><div><label>Nome completo<input name="name" maxLength={160} autoComplete="name" /></label><label>E-mail corporativo<input name="email" type="email" required autoComplete="email" /></label><label>Perfil inicial<select name="roleKey" required defaultValue=""><option value="" disabled>Selecione</option>{roles.map(role => <option value={role.key} key={role.id}>{role.name}</option>)}</select></label><label>Validade do link<select name="expiresInDays" defaultValue="7"><option value="1">24 horas</option><option value="3">3 dias</option><option value="7">7 dias</option><option value="15">15 dias</option><option value="30">30 dias</option></select></label><aside><strong>Como funciona</strong><p>O link é mostrado uma única vez. Um novo usuário define uma senha forte; uma conta existente confirma o acesso autenticada.</p></aside></div><footer><button type="button" onClick={close}>Cancelar</button><button className={styles.primary} disabled={busy}>{busy ? "Emitindo…" : "Criar convite seguro"}</button></footer></form></ErpModal>; }

function RoleDialog({ role, resources, busy, close, submit }: { role?: Role; resources: Data["permissionResources"]; busy: boolean; close: () => void; submit: (payload: Record<string, unknown>) => Promise<void> }) {
  const expanded = role?.permissions.includes("*") || role?.permissions.includes("*.write") ? resources.flatMap(item => [`${item.key}.read`, `${item.key}.write`]) : role?.permissions.includes("*.read") ? [...resources.map(item => `${item.key}.read`), ...role.permissions.filter(item => !item.startsWith("*."))] : role?.permissions || [];
  const [permissions, setPermissions] = useState(new Set(expanded)), [filter, setFilter] = useState(""), [active, setActive] = useState(role?.active ?? true);
  const visible = resources.filter(item => item.label.toLocaleLowerCase("pt-BR").includes(filter.toLocaleLowerCase("pt-BR")));
  function toggle(resource: string, action: "read" | "write") { setPermissions(current => { const next = new Set(current), key = `${resource}.${action}`; if (next.has(key)) { next.delete(key); if (action === "read") next.delete(`${resource}.write`); } else { next.add(key); if (action === "write") next.add(`${resource}.read`); } return next; }); }
  function preset(kind: "read" | "none" | "full") { setPermissions(new Set(kind === "none" ? [] : resources.flatMap(item => kind === "read" ? [`${item.key}.read`] : [`${item.key}.read`, `${item.key}.write`]))); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await submit({ ...Object.fromEntries(new FormData(event.currentTarget)), key: role?.key, permissions: [...permissions], active }); }
  return <ErpModal close={close} className={styles.modalLayer} label={role ? `Configurar ${role.name}` : "Criar perfil de acesso"}><form className={styles.roleDialog} onSubmit={save}><header><div><span>MATRIZ DE MENOR PRIVILÉGIO</span><h2>{role ? `Configurar ${role.name}` : "Novo perfil de acesso"}</h2><p>Escrita concede também a consulta do recurso correspondente.</p></div><button type="button" onClick={close} aria-label="Fechar">×</button></header><div className={styles.roleFields}><label>Nome do perfil<input name="name" defaultValue={role?.name || ""} required maxLength={100} /></label>{!role && <label>Identificador<input name="key" placeholder="gerado-pelo-nome" maxLength={50} /></label>}<label className={styles.wide}>Descrição<input name="description" defaultValue={role?.description || ""} maxLength={500} /></label><label className={styles.switch}><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} /><span>Perfil ativo para atribuição</span></label></div><section className={styles.permissionTools}><label>Buscar recurso<input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Ex.: financeiro" /></label><div><button type="button" onClick={() => preset("read")}>Somente leitura</button><button type="button" onClick={() => preset("full")}>Acesso integral</button><button type="button" onClick={() => preset("none")}>Limpar</button></div></section><section className={styles.permissionMatrix}><header><strong>Recurso</strong><span>Consultar</span><span>Alterar</span></header>{visible.map(resource => <div key={resource.key}><strong>{resource.label}</strong><input type="checkbox" checked={permissions.has(`${resource.key}.read`)} onChange={() => toggle(resource.key,"read")} aria-label={`Consultar ${resource.label}`} /><input type="checkbox" checked={permissions.has(`${resource.key}.write`)} onChange={() => toggle(resource.key,"write")} aria-label={`Alterar ${resource.label}`} /></div>)}</section><footer><span>{permissions.size} permissão(ões) selecionada(s)</span><div><button type="button" onClick={close}>Cancelar</button><button className={styles.primary} disabled={busy}>{busy ? "Salvando…" : "Salvar perfil"}</button></div></footer></form></ErpModal>;
}

function Avatar({ name }: { name: string }) { const initials = name.split(/\s+/).slice(0,2).map(part => part[0]).join("").toLocaleUpperCase("pt-BR"); return <i className={styles.avatar} aria-hidden="true">{initials || "?"}</i>; }
function Status({ value }: { value: string }) { return <span className={`${styles.badge} ${styles[value] || ""}`}>{statusLabels[value] || value}</span>; }
function ScoreCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><small>{label}</small><strong>{value}</strong><span>{detail}</span></article>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className={styles.empty}><b>◇</b><strong>{title}</strong><p>{text}</p></div>; }
function Loading() { return <div className={styles.loading}><div /><div /><div /><section /></div>; }
function Fatal({ message, retry }: { message: string; retry: () => void }) { return <section className={styles.fatal}><ErpIcon name="users" /><h2>Não foi possível abrir a central</h2><p>{message}</p><button onClick={retry}>Tentar novamente</button></section>; }
function relative(value: string) { const target = new Date(value).getTime(), diff = target - Date.now(), abs = Math.abs(diff), formatter = new Intl.RelativeTimeFormat("pt-BR", { numeric: "auto" }); if (abs < 60_000) return formatter.format(Math.round(diff / 1_000), "second"); if (abs < 3_600_000) return formatter.format(Math.round(diff / 60_000), "minute"); if (abs < 86_400_000) return formatter.format(Math.round(diff / 3_600_000), "hour"); return formatter.format(Math.round(diff / 86_400_000), "day"); }
function localDate(value: string) { const date = new Date(value), year = date.getFullYear(), month = String(date.getMonth()+1).padStart(2,"0"), day = String(date.getDate()).padStart(2,"0"); return `${year}-${month}-${day}`; }
function today() { return localDate(new Date().toISOString()); }
