import { randomUUID } from "node:crypto";
import { Prisma } from "@/generated/tenant/client";
import { currentOrganization, tenantDb } from "@/db";
import { AuthError, authErrorResponse } from "@/lib/auth";
import { LicenseDeniedError } from "@/lib/billing/license";
import { duplicateSupplierGroups, parseSupplierQuery, supplierCsv, supplierHealth, supplierPerformance } from "@/lib/erp/supplier-control";
import { supplierIds, supplierInput, SupplierInputError } from "@/lib/erp/supplier-input";
import { assertSameOrigin } from "@/lib/erp/customer-input";
import { assertTenantPermission, matches } from "@/lib/erp/permissions";
import { assertPosMutationRequest, enforcePosRateLimit, PosHttpError, readPosJson } from "@/lib/erp/pos-http";
import { enqueueWebhook } from "@/lib/integrations/webhooks";
import { assertTenantWriteAccess } from "@/lib/tenant-access";

export const dynamic = "force-dynamic";
const NO_STORE = { "cache-control": "private, no-store, max-age=0", expires: "0", pragma: "no-cache" };
const supplierInclude = {
  addresses: { where: { primary: true }, orderBy: { id: "asc" as const }, take: 1 },
  contacts: { where: { archivedAt: null }, orderBy: [{ primary: "desc" as const }, { name: "asc" as const }], take: 3 },
  tagLinks: { include: { tag: true }, orderBy: { createdAt: "asc" as const } },
  interactions: { where: { completedAt: null }, orderBy: [{ dueAt: "asc" as const }, { createdAt: "desc" as const }], take: 3 },
  complianceDocuments: { orderBy: [{ expiresAt: "asc" as const }, { createdAt: "desc" as const }], take: 5 },
  evaluations: { orderBy: { evaluatedAt: "desc" as const }, take: 1 },
  _count: { select: { products: true, purchaseOrders: true, purchaseInvoices: true, financialTitles: true } },
};
type Db = Awaited<ReturnType<typeof tenantDb>>;

export async function GET(request: Request) {
  try {
    const organization = await currentOrganization(), access = await assertTenantPermission(organization.id, "suppliers.read"), db = await tenantDb(organization.id);
    const query = parseSupplierQuery(new URL(request.url).searchParams), now = new Date(), attentionIds = await resolveAttention(db, query.attention, now);
    const where: Prisma.SupplierWhereInput = {
      ...(query.status ? { status: query.status } : {}), ...(query.category ? { category: query.category } : {}), ...(query.risk ? { riskRating: query.risk } : {}),
      ...(query.homologation ? { homologationStatus: query.homologation } : {}), ...(attentionIds ? { id: { in: attentionIds } } : {}),
      ...(query.search ? { OR: [{ name: { contains: query.search, mode: "insensitive" } }, { tradeName: { contains: query.search, mode: "insensitive" } }, { document: { contains: query.search.replace(/\D/g, "") } }, { email: { contains: query.search, mode: "insensitive" } }, { phone: { contains: query.search.replace(/\D/g, "") } }, { buyer: { contains: query.search, mode: "insensitive" } }, { contacts: { some: { archivedAt: null, OR: [{ name: { contains: query.search, mode: "insensitive" } }, { email: { contains: query.search, mode: "insensitive" } }] } } }] } : {}),
    };
    const computedSort = query.sort === "spend" || query.sort === "performance", orderBy: Prisma.SupplierOrderByWithRelationInput[] = query.sort === "recent" ? [{ updatedAt: "desc" }] : [{ status: "asc" }, { name: "asc" }];
    const take = query.format === "csv" || computedSort ? 10_001 : query.limit, rawItems = await db.supplier.findMany({ where, include: supplierInclude, orderBy, skip: take === query.limit ? (query.page - 1) * query.limit : 0, take });
    if (rawItems.length > 10_000) throw new SupplierInputError("A consulta excede 10.000 fornecedores. Aplique mais filtros.");
    let items = await enrichSuppliers(db, rawItems, now);
    if (query.sort === "spend") items.sort((a, b) => b.metrics.spend - a.metrics.spend || a.name.localeCompare(b.name));
    if (query.sort === "performance") items.sort((a, b) => b.metrics.performanceScore - a.metrics.performanceScore || a.name.localeCompare(b.name));
    const filteredTotal = await db.supplier.count({ where });
    if (computedSort && query.format !== "csv") items = items.slice((query.page - 1) * query.limit, query.page * query.limit);
    if (query.format === "csv") return new Response(supplierCsv(items.map((item) => ({ ...item, city: item.addresses[0]?.city, state: item.addresses[0]?.state, ...item.metrics }))), { headers: { ...NO_STORE, "content-type": "text/csv; charset=utf-8", "content-disposition": `attachment; filename="fornecedores-${now.toISOString().slice(0, 10)}.csv"` } });

    const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 5, 1)), thirtyDaysAgo = new Date(now.valueOf() - 30 * 86_400_000), documentLimit = new Date(now.valueOf() + 30 * 86_400_000);
    const [total, active, approved, new30d, spend, payables, overdue, averageScores, categories, risks, homologations, created, missingEmail, missingPhone, missingAddress, pendingDocuments, duplicateCandidates, tags, productLinks, topOrders] = await Promise.all([
      db.supplier.count(), db.supplier.count({ where: { status: "active" } }), db.supplier.count({ where: { homologationStatus: "approved", status: "active" } }), db.supplier.count({ where: { createdAt: { gte: thirtyDaysAgo } } }),
      db.purchaseOrder.aggregate({ where: { status: { notIn: ["draft", "cancelled"] } }, _sum: { total: true } }), db.financialTitle.aggregate({ where: { type: "payable", status: { in: ["open", "partial", "overdue"] } }, _sum: { amount: true, paidAmount: true } }),
      db.financialTitle.aggregate({ where: { type: "payable", status: { in: ["open", "partial", "overdue"] }, dueAt: { lt: now } }, _sum: { amount: true, paidAmount: true } }), db.supplierEvaluation.aggregate({ _avg: { qualityScore: true, deliveryScore: true, commercialScore: true, complianceScore: true } }),
      db.supplier.groupBy({ by: ["category"], _count: { _all: true } }), db.supplier.groupBy({ by: ["riskRating"], _count: { _all: true } }), db.supplier.groupBy({ by: ["homologationStatus"], _count: { _all: true } }), db.supplier.findMany({ where: { createdAt: { gte: monthStart } }, select: { createdAt: true } }),
      db.supplier.count({ where: { OR: [{ email: null }, { email: "" }] } }), db.supplier.count({ where: { OR: [{ phone: null }, { phone: "" }] } }), db.supplier.count({ where: { addresses: { none: {} } } }), db.supplierDocument.count({ where: { OR: [{ status: { in: ["expired", "pending", "rejected"] } }, { expiresAt: { lte: documentLimit } }] } }),
      db.supplier.findMany({ select: { id: true, name: true, email: true, phone: true }, take: 10_000 }), db.supplierTag.findMany({ orderBy: { name: "asc" } }), db.supplierProduct.count(),
      db.purchaseOrder.groupBy({ by: ["supplierId"], where: { status: { notIn: ["draft", "cancelled"] } }, _sum: { total: true }, orderBy: { _sum: { total: "desc" } }, take: 5 }),
    ]);
    const topNames = await db.supplier.findMany({ where: { id: { in: topOrders.map((item) => item.supplierId) } }, select: { id: true, name: true, tradeName: true } }), nameMap = new Map(topNames.map((item) => [item.id, item.tradeName || item.name]));
    const openPayables = (payables._sum.amount || 0) - (payables._sum.paidAmount || 0), overduePayables = (overdue._sum.amount || 0) - (overdue._sum.paidAmount || 0), averagePerformance = supplierPerformance({ qualityScore: averageScores._avg.qualityScore || 0, deliveryScore: averageScores._avg.deliveryScore || 0, commercialScore: averageScores._avg.commercialScore || 0, complianceScore: averageScores._avg.complianceScore || 0 });
    const duplicates = duplicateSupplierGroups(duplicateCandidates);
    return Response.json({
      items, tags, duplicates, generatedAt: now.toISOString(), capabilities: { canWrite: matches(access.permissions, "suppliers.write") }, pagination: { page: query.page, limit: query.limit, total: filteredTotal, pages: Math.max(1, Math.ceil(filteredTotal / query.limit)) },
      summary: { total, active, approved, new30d, spend: spend._sum.total || 0, openPayables, overduePayables, averagePerformance, linkedProducts: productLinks },
      analytics: { categories, risks, homologations, growth: growthSeries(created.map((item) => item.createdAt), now), quality: { missingEmail, missingPhone, missingAddress, pendingDocuments, duplicateGroups: duplicates.length }, topSuppliers: topOrders.map((item) => ({ id: item.supplierId, name: nameMap.get(item.supplierId) || "Fornecedor", spend: item._sum.total || 0 })) },
    }, { headers: NO_STORE });
  } catch (error) { return failure(error, "consultar"); }
}

export async function POST(request: Request) {
  try {
    assertSameOrigin(request); assertPosMutationRequest(request);
    const organization = await currentOrganization(), access = await assertTenantPermission(organization.id, "suppliers.write"); await assertTenantWriteAccess(organization.id);
    const db = await tenantDb(organization.id), body = await readPosJson(request, 1_048_576), correlationId = randomUUID(); await enforcePosRateLimit(db, access.user.id, "suppliers.mutation");
    if (body.action === "import") {
      if (!Array.isArray(body.rows) || body.rows.length < 1 || body.rows.length > 500) throw new SupplierInputError("A importação deve conter entre 1 e 500 fornecedores.");
      const inputs = body.rows.map((row, index) => { try { return supplierInput(row); } catch (error) { if (error instanceof SupplierInputError) throw new SupplierInputError(`Linha ${index + 2}: ${error.message}`); throw error; } }), updateExisting = body.mode === "update";
      const result = await db.$transaction(async (tx) => { let created = 0, updated = 0, skipped = 0; for (const input of inputs) { const existing = await tx.supplier.findUnique({ where: { document: input.document }, select: { id: true } }); if (existing && !updateExisting) { skipped += 1; continue; } const profile = profileData(input); if (existing) { await tx.supplier.update({ where: { id: existing.id }, data: { ...profile, version: { increment: 1 } } }); await upsertPrimaryAddress(tx, existing.id, input.address); updated += 1; } else { const saved = await tx.supplier.create({ data: { ...profile, addresses: { create: { ...input.address, label: "Principal", primary: true } } } }); await enqueueWebhook(tx, "supplier.created", { id: saved.id, status: saved.status, occurred_at: new Date().toISOString(), correlation_id: correlationId }); created += 1; } } await tx.tenantAuditEvent.create({ data: { actorId: access.user.id, action: "supplier.csv_imported", entityType: "supplier", correlationId, afterData: { created, updated, skipped, total: inputs.length, mode: updateExisting ? "update" : "skip" } } }); return { created, updated, skipped }; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
      return Response.json({ ...result, correlationId }, { headers: NO_STORE });
    }
    if (body.action === "batch.status" || body.action === "batch.homologation") { const ids = supplierIds(body.supplierIds), data = body.action === "batch.status" ? { status: body.status === "active" || body.status === "inactive" ? body.status : "" } : { homologationStatus: ["pending", "approved", "conditional", "rejected", "expired"].includes(String(body.homologationStatus)) ? String(body.homologationStatus) : "" }; if (!Object.values(data)[0]) throw new SupplierInputError("Situação inválida."); const changed = await db.$transaction(async (tx) => { const result = await tx.supplier.updateMany({ where: { id: { in: ids } }, data: { ...data, version: { increment: 1 } } }); await tx.tenantAuditEvent.create({ data: { actorId: access.user.id, action: body.action === "batch.status" ? "supplier.batch_status_changed" : "supplier.batch_homologation_changed", entityType: "supplier", correlationId, afterData: { ids, ...data, count: result.count } } }); return result.count; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); return Response.json({ changed, correlationId }, { headers: NO_STORE }); }
    if (body.action === "batch.tag") { const ids = supplierIds(body.supplierIds), tagId = Number(body.tagId); if (!Number.isInteger(tagId) || tagId <= 0 || !await db.supplierTag.findUnique({ where: { id: tagId }, select: { id: true } })) throw new SupplierInputError("Etiqueta inválida."); const result = await db.supplierTagLink.createMany({ data: ids.map((supplierId) => ({ supplierId, tagId })), skipDuplicates: true }); await db.tenantAuditEvent.create({ data: { actorId: access.user.id, action: "supplier.batch_tagged", entityType: "supplier", correlationId, afterData: { ids, tagId, count: result.count } } }); return Response.json({ changed: result.count, correlationId }, { headers: NO_STORE }); }
    const input = supplierInput(body), supplier = await db.$transaction(async (tx) => { const created = await tx.supplier.create({ data: { ...profileData(input), addresses: { create: { ...input.address, label: "Principal", primary: true } } }, include: supplierInclude }); await tx.tenantAuditEvent.create({ data: { actorId: access.user.id, action: "supplier.created", entityType: "supplier", entityId: String(created.id), correlationId, afterData: { name: created.name, document: created.document, status: created.status, category: created.category, homologationStatus: created.homologationStatus } } }); await enqueueWebhook(tx, "supplier.created", { id: created.id, status: created.status, occurred_at: new Date().toISOString(), correlation_id: correlationId }); return created; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
    return Response.json({ supplier, correlationId }, { status: 201, headers: NO_STORE });
  } catch (error) { return failure(error, "salvar"); }
}

function profileData(input: ReturnType<typeof supplierInput>) { const { address, ...profile } = input; void address; return profile; }
async function upsertPrimaryAddress(tx: Prisma.TransactionClient, supplierId: number, address: ReturnType<typeof supplierInput>["address"]) { const current = await tx.supplierAddress.findFirst({ where: { supplierId, primary: true }, select: { id: true } }); if (current) await tx.supplierAddress.update({ where: { id: current.id }, data: address }); else await tx.supplierAddress.create({ data: { supplierId, ...address, label: "Principal", primary: true } }); }
async function resolveAttention(db: Db, attention: string, now: Date) { if (attention === "documents") { const limit = new Date(now.valueOf() + 30 * 86_400_000); return (await db.supplierDocument.findMany({ where: { OR: [{ status: { in: ["expired", "pending", "rejected"] } }, { expiresAt: { lte: limit } }] }, distinct: ["supplierId"], select: { supplierId: true } })).map((item) => item.supplierId); } if (attention === "tasks") return (await db.supplierInteraction.findMany({ where: { completedAt: null, dueAt: { not: null } }, distinct: ["supplierId"], select: { supplierId: true } })).map((item) => item.supplierId); if (attention === "incomplete") return (await db.supplier.findMany({ where: { OR: [{ email: null }, { phone: null }, { addresses: { none: {} } }] }, select: { id: true } })).map((item) => item.id); if (attention === "pending") return (await db.supplier.findMany({ where: { homologationStatus: { in: ["pending", "conditional", "expired"] } }, select: { id: true } })).map((item) => item.id); return null; }
async function enrichSuppliers<T extends { id: number; email: string | null; phone: string | null; document: string; riskRating: string; homologationStatus: string; status: string; addresses: unknown[]; evaluations: Array<{ qualityScore: number; deliveryScore: number; commercialScore: number; complianceScore: number }> }>(db: Db, suppliers: T[], now: Date) { const ids = suppliers.map((item) => item.id); if (!ids.length) return []; const documentLimit = new Date(now.valueOf() + 30 * 86_400_000), [orders, titles, overdue, invoices, documents, tasks] = await Promise.all([db.purchaseOrder.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids }, status: { notIn: ["draft", "cancelled"] } }, _sum: { total: true }, _count: { _all: true }, _max: { createdAt: true } }), db.financialTitle.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids }, type: "payable", status: { in: ["open", "partial", "overdue"] } }, _sum: { amount: true, paidAmount: true } }), db.financialTitle.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids }, type: "payable", status: { in: ["open", "partial", "overdue"] }, dueAt: { lt: now } }, _sum: { amount: true, paidAmount: true } }), db.purchaseInvoice.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids } }, _count: { _all: true }, _max: { issueDate: true } }), db.supplierDocument.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids }, OR: [{ status: { in: ["expired", "pending", "rejected"] } }, { expiresAt: { lte: documentLimit } }] }, _count: { _all: true } }), db.supplierInteraction.groupBy({ by: ["supplierId"], where: { supplierId: { in: ids }, completedAt: null }, _count: { _all: true } })]); const byId = <TValue extends { supplierId: number | null }>(values: TValue[]) => new Map(values.flatMap((value) => value.supplierId == null ? [] : [[value.supplierId, value] as const])), orderMap = byId(orders), titleMap = byId(titles), overdueMap = byId(overdue), invoiceMap = byId(invoices), documentMap = byId(documents), taskMap = byId(tasks); return suppliers.map((supplier) => { const order = orderMap.get(supplier.id), title = titleMap.get(supplier.id), late = overdueMap.get(supplier.id), invoice = invoiceMap.get(supplier.id), evaluation = supplier.evaluations[0], performanceScore = supplierPerformance(evaluation), expiringDocuments = documentMap.get(supplier.id)?._count._all || 0, pendingTasks = taskMap.get(supplier.id)?._count._all || 0, metrics = { spend: order?._sum.total || 0, orders: order?._count._all || 0, invoices: invoice?._count._all || 0, openPayables: (title?._sum.amount || 0) - (title?._sum.paidAmount || 0), overduePayables: (late?._sum.amount || 0) - (late?._sum.paidAmount || 0), lastPurchaseAt: later(order?._max.createdAt, invoice?._max.issueDate), performanceScore, expiringDocuments, pendingTasks }, health = supplierHealth({ ...supplier, ...metrics }); return { ...supplier, metrics, health }; }); }
function later(a?: Date | null, b?: Date | null) { if (!a) return b || null; if (!b) return a; return a > b ? a : b; }
function growthSeries(values: Date[], now: Date) { return Array.from({ length: 6 }, (_, offset) => { const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 5 + offset, 1)), next = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 1)); return { month: date.toLocaleDateString("pt-BR", { month: "short", timeZone: "UTC" }).replace(".", ""), count: values.filter((value) => value >= date && value < next).length }; }); }
function failure(error: unknown, operation: string) { if (error instanceof SupplierInputError) return Response.json({ error: error.message }, { status: error.message.includes("Origem") ? 403 : 400, headers: NO_STORE }); if (error instanceof PosHttpError) return Response.json({ error: error.message.replaceAll("PDV", "módulo de fornecedores") }, { status: error.status, headers: NO_STORE }); if (error instanceof LicenseDeniedError) return Response.json({ error: error.message }, { status: error.status, headers: NO_STORE }); if (error && typeof error === "object" && "code" in error && error.code === "P2002") return Response.json({ error: "Já existe um fornecedor com este CPF ou CNPJ." }, { status: 409, headers: NO_STORE }); if (error instanceof AuthError) return authErrorResponse(error); console.error(`supplier ${operation} request failed`, error instanceof Error ? error.name : "unknown"); return Response.json({ error: `Não foi possível ${operation} os fornecedores.` }, { status: 500, headers: NO_STORE }); }
