"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import Link from "next/link";
import type {FormEvent} from 'react';
import {useEffect,useState} from 'react';

export default function BillingManager(){
  const[data,setData]=useState<any>();const[message,setMessage]=useState('');
  async function load(){setMessage("");try{const r=await fetch('/api/admin/billing',{cache:"no-store"});if(!r.ok)throw new Error("Não foi possível carregar a integração financeira.");setData(await r.json())}catch(error){setMessage(error instanceof Error?error.message:"Falha de conexão.")}}
  useEffect(()=>{load()},[]);
  async function action(name:string,extra:Record<string,unknown>={}){setMessage('Executando…');try{const r=await fetch('/api/admin/billing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:name,...extra})});const d=await r.json();if(r.ok)await load();setMessage(r.ok?'Operação concluída e auditada.':d.error||'Falha na operação.');return r.ok}catch(error){setMessage(error instanceof Error?error.message:"Falha de conexão.");return false}}
  async function saveConfiguration(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));try{await action('configuration.save',values)}finally{for(const name of ['apiKey','currentPassword']){const input=form.elements.namedItem(name) as HTMLInputElement|null;if(input)input.value=''}}}
  async function importWebhook(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));try{if(await action('webhook.import',values))form.reset()}finally{for(const name of ['webhookSecret','currentPassword']){const input=form.elements.namedItem(name) as HTMLInputElement|null;if(input)input.value=''}}}
  if(!data)return <div className="module-loading">{message?<><p role="alert">{message}</p><button onClick={()=>void load()}>Tentar novamente</button></>:<span role="status">Carregando integração financeira…</span>}</div>;
  const c=data.configuration;
  const canReprocess=(account:any)=>account.externalId===account.organizationId && !data.jobs.some((job:any)=>job.organizationId===account.organizationId && job.errorCode==='HTTP_409');
  return <>
    <div className="module-heading"><div><p>INTEGRAÇÃO HEADLESS 3.0.1 · PACOTE 3.0.3</p><h1>Financeiro externo</h1><span>Conexão com o Billing Expresso. Cobranças e pagamentos são realizados no sistema externo, não neste painel.</span></div><div className="page-actions"><button onClick={()=>action('test')}>Testar conexão</button><button className="primary" onClick={()=>action('reconcile')}>Reconciliar tenants</button></div></div>
    {message&&<div className="save-notice">{message}</div>}
    <section className="control-panel"><h2>Identidade e prevenção de duplicidades</h2><p>Novos vínculos usam o ID interno imutável da organização, nunca o nome ou slug. CPF/CNPJ é obrigatório; use o mesmo e-mail do responsável já cadastrado no Billing e nos demais produtos.</p><p><strong>Conflito 409: pare e regularize o vínculo no painel administrativo do Billing.</strong> O Nalven não repete nem tenta reconciliar automaticamente esse provisionamento. A conexão usa exclusivamente a API headless <code>/api/v1/saas</code>, nunca <code>/api/external/*</code>.</p>{data.accounts.filter((account:any)=>account.externalId!==account.organizationId).map((account:any)=><p className="integration-warning" key={account.id}><strong>{account.organization.name}: vínculo legado.</strong> O identificador atual foi preservado para não criar outra instância. Regularize o vínculo no Billing antes de reprovisionar.</p>)}</section>
    <section className="billing-config-grid"><article><small>API headless</small><strong>{c.credentialConfigured?'Credencial configurada':'Aguardando credencial'}</strong><p>{c.credential?.maskedValue||'Nenhuma chave salva'}</p></article><article><small>Webhook HMAC</small><strong>{c.webhookConfigured?'Configurado':'Não configurado'}</strong><p>{c.webhook?.maskedValue||'Importe a exibição única do Billing'}</p></article><article><small>Contas vinculadas</small><strong>{data.accounts.filter((x:any)=>x.remoteStatus==='linked').length} / {data.accounts.length}</strong><p>{data.jobs.filter((x:any)=>x.status!=='completed').length} jobs aguardando ou exigindo atenção</p></article><article><small>Eventos recebidos</small><strong>{data.events.length}</strong><p>Deduplicação por X-Webhook-Id</p></article></section>
    <section className="control-panel activation-guide"><header><div><small>CERIMÔNIA SEM SSH</small><h2>Ativação segura entre os dois cofres</h2></div><span>Billing 3.0.3</span></header><ol><li>Abra no Billing: Produtos → NALVEN → Integração segura.</li><li>Emita a credencial com 14 escopos, produção e 300 req/min.</li><li>Cole abaixo a chave e o fingerprint exibidos uma única vez.</li><li>Gere/rotacione o HMAC no Billing e importe no segundo formulário.</li><li>Confirme fingerprints, teste a conexão e depois reconcilie os tenants.</li><li>No Billing, use “Testar e ativar” para liberar o webhook.</li></ol></section>
    <section className="control-panel vault-panel"><header><div><small>COFRE CRIPTOGRAFADO</small><h2>API do produto</h2><p>A chave é cifrada com AES-256-GCM; depois da gravação somente máscara e fingerprint ficam visíveis.</p></div><span className="vault-badge">Somente superadmin</span></header><form className="billing-settings-form" onSubmit={saveConfiguration}><label>API principal<input name="baseUrl" type="url" defaultValue={c.baseUrl} required/></label><label>API headless<input name="headlessBaseUrl" type="url" defaultValue={c.headlessBaseUrl} required/></label><label>URL pública do NALVEN<input name="publicAppUrl" type="url" defaultValue={c.publicAppUrl} required/></label><label>Código do produto<input name="productCode" defaultValue={c.productCode} required/></label><label>Versão da aplicação<input name="appVersion" defaultValue={c.appVersion} required/></label><Link href="/admin/licencas">Configurar política de licença →</Link><span/>
      <label className="secret-field">Chave permanente do produto<input name="apiKey" type="password" autoComplete="new-password" placeholder={c.credentialConfigured?'Deixe vazio para manter a chave atual':'skp_nalven_…'}/><small>{c.credential?`Fingerprint ${c.credential.fingerprint} · atualizada em ${new Date(c.credential.updatedAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}`:'Ainda não configurada'}</small></label>
      <label>Fingerprint informado pelo Billing<input name="apiKeyFingerprint" inputMode="text" maxLength={16} placeholder="16 caracteres SHA-256"/></label><label>Confirme sua senha administrativa<input name="currentPassword" type="password" autoComplete="current-password" required placeholder="Obrigatória para salvar a configuração"/></label><div className="billing-form-actions"><button className="primary">Salvar configuração</button></div></form></section>
    <section className="control-panel vault-panel"><header><div><small>WEBHOOK ASSINADO</small><h2>Importar HMAC gerado no Billing</h2><p>A divergência de fingerprint é rejeitada antes de qualquer alteração. O segredo nunca é devolvido pelo NALVEN.</p></div><span className="vault-badge">Sem reinício</span></header><form className="webhook-import-form" onSubmit={importWebhook}><label className="secret-field">Segredo em exibição única<input name="webhookSecret" type="password" autoComplete="new-password" required placeholder="Cole diretamente do cofre Billing"/></label><label>Fingerprint do Billing<input name="expectedFingerprint" maxLength={16} required placeholder="Ex.: 2d01107bcefaac01"/></label><label>Confirme sua senha administrativa<input name="currentPassword" type="password" autoComplete="current-password" required/></label><button className="primary">Validar fingerprint e cifrar</button></form><div className="webhook-control"><div><strong>Receptor de webhook</strong><code>{c.webhookUrl}</code><small>{c.webhook?`Fingerprint atual ${c.webhook.fingerprint} · atualizada em ${new Date(c.webhook.updatedAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}`:'Nenhum segredo importado'}</small></div><span className={`sync-status ${c.webhookConfigured?'linked':'pending'}`}>{c.webhookConfigured?'Pronto para teste assinado':'Aguardando importação'}</span></div></section>
    {!c.credentialConfigured&&<section className="integration-warning"><strong>Credencial permanente necessária</strong><p>Emita no Billing uma chave <code>skp_nalven_…</code> e cole no formulário acima com seu fingerprint. Ela nunca ficará no <code>.env</code>.</p></section>}
    <section className="control-panel"><div className="table-tools"><strong>Organizações vinculadas</strong><span>{data.accounts.length} contas</span></div><div className="admin-table-wrap"><table><thead><tr><th>Organização</th><th>External ID</th><th>Estado remoto</th><th>Plano</th><th>Assinatura</th><th>Última sincronização</th><th>Ações</th></tr></thead><tbody>{data.accounts.map((x:any)=><tr key={x.id}><td><strong>{x.organization.name}</strong>{x.lastError&&<small className="row-error">{x.lastError}</small>}</td><td>{x.externalId}</td><td><span className={`sync-status ${x.remoteStatus}`}>{statusLabel(x.remoteStatus)}</span></td><td>{x.planCode||'—'}</td><td>{x.subscriptionStatus||'—'}</td><td>{x.lastSyncedAt?new Date(x.lastSyncedAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' }):'—'}</td><td><div className="row-button-group"><button onClick={()=>action('sync',{organizationId:x.organizationId})}>Sincronizar</button><button disabled={!canReprocess(x)} title={!canReprocess(x)?'Regularize a identidade e o vínculo no painel administrativo do Billing.':undefined} onClick={()=>action('retry_provision',{organizationId:x.organizationId})}>Reprocessar</button></div></td></tr>)}</tbody></table></div></section>
    <section className="control-panel billing-jobs"><div className="table-tools"><strong>Fila resiliente de provisionamento</strong><span>{data.jobs.length} execuções</span></div><div className="admin-table-wrap"><table><thead><tr><th>Organização</th><th>Estado</th><th>Tentativas</th><th>Próxima execução</th><th>Último erro</th></tr></thead><tbody>{data.jobs.map((job:any)=>{const account=data.accounts.find((x:any)=>x.organizationId===job.organizationId);return <tr key={job.id}><td>{account?.organization.name||job.organizationId}</td><td><span className={`sync-status ${job.status}`}>{statusLabel(job.status)}</span></td><td>{job.attempts}</td><td>{job.status==='completed'?'Concluído':['pending','retry'].includes(job.status)?new Date(job.nextAttemptAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' }):'Sem nova tentativa agendada'}</td><td>{job.errorCode==='HTTP_409'?'Conflito 409: regularize documento, e-mail e vínculo no painel administrativo do Billing.':job.lastError||'—'}</td></tr>})}</tbody></table></div></section>
    <section className="control-panel billing-events"><div className="table-tools"><strong>Webhooks recentes</strong><span>{data.events.length} eventos</span></div>{data.events.slice(0,20).map((x:any)=><div key={x.webhookId}><strong>{x.event}</strong><span>{x.externalId||'—'}</span><small>{new Date(x.receivedAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}</small></div>)}</section>
  </>;
}
function statusLabel(value:string){return({linked:'Vinculado',pending:'Pendente',processing:'Processando',retry:'Nova tentativa',retrying:'Nova tentativa',blocked:'Aguardando configuração',failed:'Requer correção',missing:'Ausente no Billing',completed:'Concluído'} as Record<string,string>)[value]||value}
