import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/tenant/client";

if (process.env.NALVEN_ALLOW_DEMO_BRANCH_SEED !== "1") throw new Error("Defina NALVEN_ALLOW_DEMO_BRANCH_SEED=1 para confirmar o seed demonstrativo de empresas e filiais.");
const tenantUrl = process.env.TENANT_DATABASE_URL;
if (!tenantUrl) throw new Error("TENANT_DATABASE_URL é obrigatória.");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: tenantUrl }) });
const DAY = 86_400_000;
const now = new Date();
const businessHours = [
  { day: 0, enabled: false, opensAt: "09:00", closesAt: "13:00" },
  { day: 1, enabled: true, opensAt: "08:00", closesAt: "18:00" },
  { day: 2, enabled: true, opensAt: "08:00", closesAt: "18:00" },
  { day: 3, enabled: true, opensAt: "08:00", closesAt: "18:00" },
  { day: 4, enabled: true, opensAt: "08:00", closesAt: "18:00" },
  { day: 5, enabled: true, opensAt: "08:00", closesAt: "18:00" },
  { day: 6, enabled: true, opensAt: "08:00", closesAt: "12:00" },
];
const branchRows = [
  { code: "MATRIZ", name: "Matriz Chapecó", legalName: "Auto Mais Peças Ltda.", document: cnpj("114447770001"), type: "headquarters", status: "active", city: "Chapecó", state: "SC", zip: "89801001", street: "Avenida Getúlio Vargas", number: "1840", district: "Centro", activityCode: "4530703", stateRegistration: "257445890", costCenterCode: "CC-MATRIZ", managerName: "Mariana Costa", managerEmail: "mariana@demo.nalven.com.br", managerPhone: "49999100101", email: "matriz@demo.nalven.com.br", phone: "4933221100", warehouseCode: "PRINCIPAL", warehouseName: "Estoque principal", taxRegime: "simples_nacional", fiscalEnvironment: "homologation", capabilities: [true, true, true, true, true] },
  { code: "CENTRO", name: "Filial Centro Lages", legalName: "Auto Mais Peças Ltda.", document: cnpj("837465920001"), type: "branch", status: "active", city: "Lages", state: "SC", zip: "88501000", street: "Rua Correia Pinto", number: "348", district: "Centro", activityCode: "4530703", stateRegistration: "250774612", costCenterCode: "CC-LAGES", managerName: "Camila Rocha", managerEmail: "camila.lages@demo.nalven.com.br", managerPhone: "49999100606", email: "lages@demo.nalven.com.br", phone: "4932216600", warehouseCode: "DEP-CENTRO", warehouseName: "Depósito Lages", taxRegime: "simples_nacional", fiscalEnvironment: "homologation", capabilities: [true, true, true, true, true] },
  { code: "FILIAL-FLORIPA", name: "Filial Florianópolis", legalName: "Auto Mais Peças Ltda.", document: cnpj("102938470001"), type: "branch", status: "active", city: "Florianópolis", state: "SC", zip: "88015000", street: "Rua Felipe Schmidt", number: "735", district: "Centro", activityCode: "4530703", stateRegistration: "261884720", costCenterCode: "CC-FLN", managerName: "Lucas Menezes", managerEmail: "lucas.fln@demo.nalven.com.br", managerPhone: "48999100202", email: "florianopolis@demo.nalven.com.br", phone: "4832212200", warehouseCode: "DEP-FLORIPA", warehouseName: "Depósito Florianópolis", taxRegime: "simples_nacional", fiscalEnvironment: "homologation", capabilities: [true, true, true, true, true] },
  { code: "FILIAL-JOINVILLE", name: "Filial Joinville", legalName: "Auto Mais Peças Ltda.", document: cnpj("293847560001"), type: "branch", status: "active", city: "Joinville", state: "SC", zip: "89201000", street: "Rua do Príncipe", number: "414", district: "Centro", activityCode: "4530703", stateRegistration: "262910443", costCenterCode: "CC-JOI", managerName: "Fernanda Luz", managerEmail: "fernanda.joi@demo.nalven.com.br", managerPhone: "47999100303", email: "joinville@demo.nalven.com.br", phone: "4734223300", warehouseCode: "DEP-JOINVILLE", warehouseName: "Depósito Joinville", taxRegime: "lucro_presumido", fiscalEnvironment: "homologation", capabilities: [true, true, true, true, false] },
  { code: "CD-SUL", name: "Centro de Distribuição Sul", legalName: "Auto Mais Logística Ltda.", document: cnpj("384756290001"), type: "headquarters", status: "active", city: "São José", state: "SC", zip: "88103000", street: "Rodovia BR-101", number: "9800", district: "Distrito Industrial", activityCode: "5211701", stateRegistration: "263775120", costCenterCode: "CC-CDSUL", managerName: "Rafael Moraes", managerEmail: "rafael.cd@demo.nalven.com.br", managerPhone: "48999100404", email: "cdsul@demo.nalven.com.br", phone: "4830334400", warehouseCode: "DEP-CD-SUL", warehouseName: "CD Sul", taxRegime: "lucro_real", fiscalEnvironment: "homologation", capabilities: [false, true, true, true, false] },
  { code: "LOJA-OESTE", name: "Loja Oeste", legalName: "Auto Mais Peças Ltda.", document: cnpj("475629380001"), type: "branch", status: "inactive", city: "Xanxerê", state: "SC", zip: "89820000", street: "Avenida Brasil", number: "620", district: "Centro", activityCode: "4530703", stateRegistration: "258901337", costCenterCode: "CC-OESTE", managerName: "Paula Dias", managerEmail: "paula.oeste@demo.nalven.com.br", managerPhone: "49999100505", email: "oeste@demo.nalven.com.br", phone: "4934335500", warehouseCode: "DEP-OESTE", warehouseName: "Depósito Oeste", taxRegime: "simples_nacional", fiscalEnvironment: "homologation", capabilities: [false, false, false, false, false] },
  { code: "NOVA-UNIDADE", name: "Nova Unidade Blumenau", legalName: "Auto Mais Peças Ltda.", document: cnpj("562938470001"), type: "branch", status: "planned", city: "Blumenau", state: "SC", zip: null, street: null, number: null, district: null, activityCode: null, stateRegistration: null, costCenterCode: "CC-BNU", managerName: null, managerEmail: null, managerPhone: null, email: "implantacao@demo.nalven.com.br", phone: null, warehouseCode: null, warehouseName: null, taxRegime: "simples_nacional", fiscalEnvironment: "homologation", capabilities: [true, false, false, false, false] },
] as const;

async function main() {
  const [identity] = await db.$queryRawUnsafe<Array<{ database: string; role: string }>>("SELECT current_database() AS database, current_user AS role");
  if (!identity || identity.database !== "nalven_t_demo" || identity.role !== "nalven_t_demo_runtime") throw new Error("O seed de empresas e filiais só pode executar em nalven_t_demo com a credencial runtime.");
  const profiles = await db.tenantUserProfile.findMany({ where: { status: "active" }, orderBy: { id: "asc" } }), products = await db.product.findMany({ where: { active: true }, orderBy: { id: "asc" }, take: 80 });
  const actorId = profiles[0]?.userId || "demo-branch-seed", branches = new Map<string, Awaited<ReturnType<typeof db.branch.upsert>>>();
  for (const row of branchRows) {
    const warehouseCode: string | null = row.warehouseCode, warehouseName: string | null = row.warehouseName;
    const warehouse = warehouseCode ? await db.warehouse.upsert({ where: { code: warehouseCode }, update: { name: warehouseName || warehouseCode, active: true, description: `Estrutura demonstrativa de ${row.name}.` }, create: { code: warehouseCode, name: warehouseName || warehouseCode, active: true, primary: row.code === "MATRIZ", description: `Estrutura demonstrativa de ${row.name}.` } }) : null;
    const [salesEnabled, purchasesEnabled, stockEnabled, fiscalEnabled, servicesEnabled] = row.capabilities;
    const common = { name: row.name, legalName: row.legalName, document: row.document, type: row.type, status: row.status, openingDate: row.status === "planned" ? new Date(now.valueOf() + 75 * DAY) : new Date("2022-03-14T00:00:00.000Z"), activityCode: row.activityCode, notes: row.status === "planned" ? "Implantação em andamento: endereço, depósito e equipe ainda precisam ser definidos." : `Unidade demonstrativa ${row.name} com dados integrados para avaliação.`, stateRegistration: row.stateRegistration, stateRegistrationExempt: false, email: row.email, phone: row.phone, managerName: row.managerName, managerEmail: row.managerEmail, managerPhone: row.managerPhone, costCenterCode: row.costCenterCode, zip: row.zip, street: row.street, number: row.number, district: row.district, city: row.city, state: row.state, timezone: "America/Sao_Paulo", defaultWarehouseId: warehouse?.id || null };
    const settings = { taxRegime: row.taxRegime, fiscalEnvironment: row.fiscalEnvironment, reserveStockOnOrder: true, allowCrossBranchFulfillment: row.type === "branch", autoTransferEnabled: row.code !== "NOVA-UNIDADE", stockAllocationStrategy: row.code === "CD-SUL" ? "highest_stock" : "local_first", salesEnabled, purchasesEnabled, stockEnabled, fiscalEnabled, servicesEnabled, businessHours };
    const branch = await db.branch.upsert({ where: { code: row.code }, update: { ...common, settings: { upsert: { update: settings, create: settings } }, version: { increment: 1 } }, create: { code: row.code, ...common, primary: false, settings: { create: settings } } });
    branches.set(row.code, branch); if (warehouse) await db.warehouse.update({ where: { id: warehouse.id }, data: { branchId: branch.id } });
  }
  const matrix = branches.get("MATRIZ"); if (!matrix) throw new Error("Matriz demo não foi criada.");
  await db.$transaction([db.branch.updateMany({ where: { primary: true, id: { not: matrix.id } }, data: { primary: false } }), db.branch.update({ where: { id: matrix.id }, data: { primary: true, parentBranchId: null } }), db.branch.updateMany({ where: { code: { in: ["CENTRO", "FILIAL-FLORIPA", "FILIAL-JOINVILLE", "LOJA-OESTE", "NOVA-UNIDADE"] } }, data: { parentBranchId: matrix.id } })]);
  for (const row of branchRows.filter((item) => item.status !== "planned")) {
    const branch = branches.get(row.code), warehouse = row.warehouseCode ? await db.warehouse.findUnique({ where: { code: row.warehouseCode } }) : null; if (!branch || !warehouse) continue;
    const catalog = row.status === "inactive" ? products.slice(0, 10) : products;
    for (const [index, product] of catalog.entries()) {
      await db.branchProduct.upsert({ where: { branchId_productId: { branchId: branch.id, productId: product.id } }, update: { active: true, saleEnabled: row.code !== "CD-SUL", purchaseEnabled: true, preferredWarehouseId: warehouse.id, minStock: 3 + index % 5, reorderPoint: 5 + index % 7, reorderQuantity: 8 + index % 12, location: `${String.fromCharCode(65 + index % 6)}-${String(index % 12 + 1).padStart(2, "0")}`, leadTimeDays: 2 + index % 9 }, create: { branchId: branch.id, productId: product.id, active: true, saleEnabled: row.code !== "CD-SUL", purchaseEnabled: true, preferredWarehouseId: warehouse.id, minStock: 3 + index % 5, reorderPoint: 5 + index % 7, reorderQuantity: 8 + index % 12, location: `${String.fromCharCode(65 + index % 6)}-${String(index % 12 + 1).padStart(2, "0")}`, leadTimeDays: 2 + index % 9 } });
      if (product.type === "product" && index < 18) await db.warehouseBalance.upsert({ where: { warehouseId_productId: { warehouseId: warehouse.id, productId: product.id } }, update: { quantity: 12 + (index * 7 + branch.id) % 54, reservedQuantity: index % 4 }, create: { warehouseId: warehouse.id, productId: product.id, quantity: 12 + (index * 7 + branch.id) % 54, reservedQuantity: index % 4 } });
    }
    const team = profiles.slice(0, row.code === "CD-SUL" ? 3 : 4); for (const profile of team) await db.branchUserAccess.upsert({ where: { branchId_userProfileId: { branchId: branch.id, userProfileId: profile.id } }, update: { canSell: row.code !== "CD-SUL", canManageStock: true, canIssueFiscal: profile.id === team[0]?.id, primary: row.code === "MATRIZ" }, create: { branchId: branch.id, userProfileId: profile.id, canSell: row.code !== "CD-SUL", canManageStock: true, canIssueFiscal: profile.id === team[0]?.id, primary: row.code === "MATRIZ" } });
    await db.financialAccount.upsert({ where: { code: `BANCO-${row.code}` }, update: { name: `Conta operacional · ${row.name}`, branchId: branch.id, active: row.status === "active" }, create: { code: `BANCO-${row.code}`, name: `Conta operacional · ${row.name}`, type: "bank", branchId: branch.id, institutionName: "Banco Demo", accountNumberLast4: String(4100 + branch.id).slice(-4), currentBalance: 18500 + branch.id * 1370, currentBalanceCents: 1_850_000 + branch.id * 137_000, openingBalance: 12000, openingBalanceCents: 1_200_000, active: row.status === "active" } });
    if (row.status === "active") await db.dfeSyncCursor.upsert({ where: { branchId_source_environment: { branchId: branch.id, source: "sefaz_nfe", environment: row.fiscalEnvironment } }, update: { enabled: true, status: "idle", lastSuccessAt: new Date(now.valueOf() - (branch.id % 4 + 1) * 3_600_000), nextSyncAt: new Date(now.valueOf() + 900_000), consecutiveFailures: 0 }, create: { branchId: branch.id, source: "sefaz_nfe", environment: row.fiscalEnvironment, enabled: true, status: "idle", lastNsu: String(8700 + branch.id).padStart(15, "0"), maxNsu: String(8700 + branch.id).padStart(15, "0"), lastSuccessAt: new Date(now.valueOf() - (branch.id % 4 + 1) * 3_600_000), nextSyncAt: new Date(now.valueOf() + 900_000) } });
    for (const kind of ["receivable", "payable"] as const) await db.financialTitle.upsert({ where: { sourceType_sourceId: { sourceType: "demo_branch", sourceId: `${row.code}:${kind}` } }, update: { branchId: branch.id }, create: { type: kind, description: kind === "receivable" ? `Carteira de clientes · ${row.name}` : `Serviços e utilidades · ${row.name}`, branchId: branch.id, sourceType: "demo_branch", sourceId: `${row.code}:${kind}`, amount: kind === "receivable" ? 4200 + branch.id * 170 : 1350 + branch.id * 95, paidAmount: kind === "receivable" ? 800 : 0, issueAt: new Date(now.valueOf() - 9 * DAY), dueAt: new Date(now.valueOf() + (kind === "receivable" ? 12 : 7) * DAY), status: kind === "receivable" ? "partial" : "open", category: kind === "receivable" ? "Vendas" : "Infraestrutura" } });
    for (let index = 1; index <= 2; index += 1) await db.salesOrder.upsert({ where: { number: `PED-${row.code}-${index}` }, update: { branchId: branch.id }, create: { number: `PED-${row.code}-${index}`, kind: "order", status: "completed", branchId: branch.id, customerName: index === 1 ? "Oficina Estrada Sul" : "Auto Center Horizonte", salesChannel: "direct", subtotal: 780 + branch.id * 31 + index * 120, total: 780 + branch.id * 31 + index * 120, createdBy: actorId, placedAt: new Date(now.valueOf() - (index * 8 + branch.id) * DAY) } });
    const existingAudit = await db.tenantAuditEvent.findFirst({ where: { entityType: "branch", entityId: String(branch.id), correlationId: `demo-branch-${row.code}` }, select: { id: true } }); if (!existingAudit) await db.tenantAuditEvent.create({ data: { actorId, action: "branch.created", entityType: "branch", entityId: String(branch.id), correlationId: `demo-branch-${row.code}`, afterData: { source: "demo_seed", code: row.code, status: row.status, scenario: row.code === "CD-SUL" ? "distribution_center" : "retail_unit" } } });
  }
  const planned = branches.get("NOVA-UNIDADE"); if (planned) { await db.branchProduct.deleteMany({ where: { branchId: planned.id } }); await db.branchUserAccess.deleteMany({ where: { branchId: planned.id } }); }
  console.log(JSON.stringify({ branches: await db.branch.count(), active: await db.branch.count({ where: { status: "active" } }), planned: await db.branch.count({ where: { status: "planned" } }), inactive: await db.branch.count({ where: { status: "inactive" } }), warehouses: await db.warehouse.count(), accessLinks: await db.branchUserAccess.count(), catalogLinks: await db.branchProduct.count() }));
}

function cnpj(base: string) { const digits = base.replace(/\D/g, "").padStart(12, "0").slice(0, 12), first = digit(digits, [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]), second = digit(`${digits}${first}`, [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]); return `${digits}${first}${second}`; }
function digit(value: string, weights: number[]) { const remainder = value.split("").reduce((sum, current, index) => sum + Number(current) * weights[index], 0) % 11; return remainder < 2 ? 0 : 11 - remainder; }

main().finally(async () => db.$disconnect());
