import { PrismaPg } from "@prisma/adapter-pg";
import { Prisma, PrismaClient } from "../generated/tenant/client";

if (process.env.NALVEN_ALLOW_DEMO_SUPPLIER_SEED !== "1") throw new Error("Defina NALVEN_ALLOW_DEMO_SUPPLIER_SEED=1 para confirmar o seed demonstrativo de fornecedores.");
const connectionString = process.env.TENANT_DATABASE_URL;
if (!connectionString) throw new Error("TENANT_DATABASE_URL não foi definida.");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString }) }), actor = "Seed fornecedores NALVEN", now = new Date(), day = (offset: number) => new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset, 12));
const names = ["Petro Sul Lubrificantes", "Filtros Catarinense", "Rota Oeste Transportes", "TechParts Sistemas", "Mecânica Planalto", "Química Serra", "Energia Comercial Sul", "Freios Premium Brasil", "Importadora Caminhos", "Log Prime Operações", "Certifica Consultoria", "Auto Elétrica Nacional", "Embalagens Vale Verde", "Cloud Mobility", "Ferramentas Horizonte", "Recicla Óleos Ambiental", "Pneus Estrada Forte", "Seguros Operacionais", "Distribuição Serra Azul", "Dados & Gestão", "Facilities Oeste", "Transporte Expresso Norte", "Componentes Mobilidade", "Suprimentos Pioneira"];
const cities = [["Joinville", "SC"], ["Blumenau", "SC"], ["Chapecó", "SC"], ["Curitiba", "PR"], ["Passo Fundo", "RS"], ["Caxias do Sul", "RS"], ["Florianópolis", "SC"], ["São Paulo", "SP"], ["Itajaí", "SC"], ["Porto Alegre", "RS"], ["Concórdia", "SC"], ["Campinas", "SP"], ["Joaçaba", "SC"], ["São José", "SC"], ["Cascavel", "PR"], ["Lages", "SC"], ["Pato Branco", "PR"], ["Curitiba", "PR"], ["Videira", "SC"], ["São Paulo", "SP"], ["Xanxerê", "SC"], ["Erechim", "RS"], ["Jaraguá do Sul", "SC"], ["Criciúma", "SC"]] as const;
const categories = ["goods", "goods", "logistics", "technology", "services", "goods", "utilities", "goods", "goods", "logistics", "services", "goods", "goods", "technology", "goods", "services", "goods", "services", "goods", "technology", "services", "logistics", "goods", "other"] as const;
const homologations = ["approved", "approved", "conditional", "approved", "pending", "approved", "approved", "approved", "conditional", "approved", "approved", "expired", "approved", "pending", "approved", "approved", "approved", "conditional", "rejected", "approved", "pending", "approved", "approved", "approved"] as const;

async function main() {
  const [identity] = await db.$queryRaw<Array<{ database: string; role: string }>>(Prisma.sql`SELECT current_database() AS database, current_user AS role`);
  if (!identity || identity.database !== "nalven_t_demo" || identity.role !== "nalven_t_demo_runtime") throw new Error("O seed de fornecedores só pode executar em nalven_t_demo com a credencial runtime.");
  const products = await db.product.findMany({ where: { active: true }, orderBy: { id: "asc" }, take: 50 });
  if (products.length < 3) throw new Error("O seed exige ao menos três produtos ativos.");
  const tags = await Promise.all([["Estratégico", "#168151"], ["Entrega rápida", "#347eac"], ["Revisão documental", "#bf6647"], ["Fornecedor local", "#765eaf"], ["Melhor custo", "#b28320"]].map(([name, color]) => db.supplierTag.upsert({ where: { name }, update: { color }, create: { name, color } })));
  for (let index = 0; index < names.length; index += 1) {
    const name = `${names[index]} Ltda.`, document = cnpj(70_000_000 + index * 3571), shared = index === 8 || index === 18, email = index === 20 ? null : shared ? "compras.compartilhadas@fornecedor.example" : `fornecedor${String(index + 1).padStart(2, "0")}@demo.example`, phone = index === 13 ? null : shared ? "4933228899" : `49${String(33220000 + index * 197).slice(-8)}`, riskRating = index === 18 ? "blocked" : [8, 11].includes(index) ? "high" : index % 4 === 0 ? "medium" : "low", [city, state] = cities[index], createdAt = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - (index % 6), 3 + index % 20, 12));
    const profile = { name, tradeName: names[index], email, phone, category: categories[index], homologationStatus: homologations[index], riskRating, buyer: index % 3 === 0 ? "Beatriz Compras" : index % 3 === 1 ? "Leonardo Suprimentos" : "Equipe de abastecimento", origin: index % 4 === 0 ? "invoice" : index % 4 === 1 ? "purchase" : index % 4 === 2 ? "referral" : "manual", taxRegime: index % 3 === 0 ? "actual" : index % 3 === 1 ? "simples" : "presumed", stateRegistration: `${250000000 + index * 913}`, paymentTerms: index % 3 === 0 ? "28/56 dias" : index % 3 === 1 ? "30 dias" : "21/42 dias", paymentTermsDays: 28 + index % 3 * 7, deliveryLeadTimeDays: 2 + index % 9, minimumOrder: 350 + index * 75, status: index === 18 ? "inactive" : "active", createdAt };
    const supplier = await db.supplier.upsert({ where: { document }, update: profile, create: { ...profile, document, website: `https://fornecedor${String(index + 1).padStart(2, "0")}.example`, notes: index % 5 === 0 ? "Parceiro acompanhado no comitê trimestral de suprimentos." : null } });
    const address = await db.supplierAddress.findFirst({ where: { supplierId: supplier.id, primary: true } }), addressData = { label: "Principal", zip: String(89800000 + index * 109), street: `Avenida Industrial ${index + 1}`, number: String(300 + index * 11), district: index % 2 ? "Centro" : "Distrito Industrial", city, state, primary: true };
    if (address) await db.supplierAddress.update({ where: { id: address.id }, data: addressData }); else if (index !== 21) await db.supplierAddress.create({ data: { supplierId: supplier.id, ...addressData } });
    const contactName = ["Carolina Comercial", "Felipe Financeiro", "Márcia Pós-venda"][index % 3], contact = await db.supplierContact.findFirst({ where: { supplierId: supplier.id, name: contactName, archivedAt: null } });
    if (!contact) { await db.supplierContact.updateMany({ where: { supplierId: supplier.id, archivedAt: null }, data: { primary: false } }); await db.supplierContact.create({ data: { supplierId: supplier.id, name: contactName, role: ["Comercial", "Financeiro", "Pós-venda"][index % 3], email, phone, primary: true } }); }
    await db.supplierTagLink.upsert({ where: { supplierId_tagId: { supplierId: supplier.id, tagId: tags[index % tags.length].id } }, update: {}, create: { supplierId: supplier.id, tagId: tags[index % tags.length].id } });
    const subject = ["Renegociar condição anual", "Confirmar capacidade de entrega", "Atualizar tabela de preços", "Revisar documentação de homologação"][index % 4];
    if (!await db.supplierInteraction.findFirst({ where: { supplierId: supplier.id, subject, createdBy: actor } })) await db.supplierInteraction.create({ data: { supplierId: supplier.id, type: index % 4 === 3 ? "task" : "negotiation", subject, notes: "Cenário demonstrativo de relacionamento com o parceiro.", dueAt: day(index % 4 === 0 ? -3 : 5 + index), completedAt: index % 7 === 0 ? day(-1) : null, createdBy: actor, createdAt: day(-index) } });
    const documentName = index % 3 === 0 ? "Certidão fiscal federal" : index % 3 === 1 ? "Certificado de qualidade" : "Licença operacional", documentType = index % 3 === 0 ? "tax" : index % 3 === 1 ? "certificate" : "license", documentStatus = index % 8 === 0 ? "expired" : index % 7 === 0 ? "pending" : "valid", expiresAt = index % 8 === 0 ? day(-5) : index % 6 === 0 ? day(18) : day(120 + index), compliance = await db.supplierDocument.findFirst({ where: { supplierId: supplier.id, name: documentName, createdBy: actor } });
    if (compliance) await db.supplierDocument.update({ where: { id: compliance.id }, data: { status: documentStatus, expiresAt } }); else await db.supplierDocument.create({ data: { supplierId: supplier.id, type: documentType, name: documentName, number: `DOC-${String(index + 1).padStart(4, "0")}`, status: documentStatus, issuedAt: day(-180), expiresAt, fileReference: `GED-DEMO-${String(index + 1).padStart(4, "0")}`, createdBy: actor } });
    if (index % 6 !== 4 && !await db.supplierEvaluation.findFirst({ where: { supplierId: supplier.id, evaluatedBy: actor } })) await db.supplierEvaluation.create({ data: { supplierId: supplier.id, qualityScore: 58 + index % 8 * 5, deliveryScore: 52 + index % 7 * 6, commercialScore: 63 + index % 6 * 5, complianceScore: homologations[index] === "approved" ? 82 + index % 4 * 4 : 45 + index % 5 * 5, notes: "Avaliação demonstrativa do ciclo atual.", evaluatedBy: actor, evaluatedAt: day(-10 - index) } });
    for (let link = 0; link < 2; link += 1) { const product = products[(index * 2 + link) % products.length]; await db.supplierProduct.upsert({ where: { supplierId_productId: { supplierId: supplier.id, productId: product.id } }, update: { supplierCode: `FOR-${index + 1}-${link + 1}`, lastCost: Math.max(1, product.cost * (0.92 + index % 5 * .02)), leadTimeDays: 2 + index % 9, minimumOrder: 6 + index % 12, preferred: link === 0 && index % 3 === 0 }, create: { supplierId: supplier.id, productId: product.id, supplierCode: `FOR-${index + 1}-${link + 1}`, lastCost: Math.max(1, product.cost * (0.92 + index % 5 * .02)), leadTimeDays: 2 + index % 9, minimumOrder: 6 + index % 12, preferred: link === 0 && index % 3 === 0 } }); }
    const product = products[index % products.length], orderTotal = 1450 + index * 875.25, number = `PC-FOR-DEMO-${String(index + 1).padStart(3, "0")}`, orderStatus = index % 5 === 0 ? "received" : index % 4 === 0 ? "partially_received" : "ordered";
    await db.purchaseOrder.upsert({ where: { number }, update: { supplierId: supplier.id, status: orderStatus, total: orderTotal, subtotal: orderTotal, expectedAt: day(index % 6 - 2), dueAt: day(20 + index), createdAt: day(-20 - index) }, create: { number, supplierId: supplier.id, status: orderStatus, expectedAt: day(index % 6 - 2), dueAt: day(20 + index), subtotal: orderTotal, total: orderTotal, notes: "Pedido demonstrativo para análise da carteira.", createdBy: actor, orderedAt: day(-20 - index), completedAt: orderStatus === "received" ? day(-2) : null, createdAt: day(-20 - index), items: { create: { productId: product.id, quantity: 10 + index, receivedQuantity: orderStatus === "received" ? 10 + index : orderStatus === "partially_received" ? 4 + index : 0, unitCost: orderTotal / (10 + index), total: orderTotal } } } });
    const amount = 980 + index * 433.75, titleStatus = index % 7 === 0 ? "paid" : index % 5 === 0 ? "partial" : "open", paidAmount = titleStatus === "paid" ? amount : titleStatus === "partial" ? Math.round(amount * .4 * 100) / 100 : 0;
    await db.financialTitle.upsert({ where: { sourceType_sourceId: { sourceType: "demo_supplier", sourceId: `SUPPLIER-${index + 1}` } }, update: { supplierId: supplier.id, amount, paidAmount, status: titleStatus, dueAt: day(index % 4 === 0 ? -10 - index : 8 + index) }, create: { type: "payable", description: `Compra demonstrativa · ${names[index]}`, supplierId: supplier.id, documentNumber: `FOR-${String(index + 1).padStart(4, "0")}`, sourceType: "demo_supplier", sourceId: `SUPPLIER-${index + 1}`, amount, paidAmount, issueAt: day(-25), dueAt: day(index % 4 === 0 ? -10 - index : 8 + index), status: titleStatus, category: "Suprimentos", priority: index % 4 === 0 ? "high" : "normal", notes: "Simulação para análise financeira do fornecedor." } });
  }
  console.log(JSON.stringify({ database: identity.database, suppliers: names.length, tags: tags.length, simulations: ["homologação", "risco", "documentos", "avaliações", "compras", "catálogo", "financeiro", "tarefas", "duplicidades"] }));
}
function cnpj(base: number) { const root = `${String(base).padStart(8, "0").slice(-8)}0001`, first = digit(root, [5,4,3,2,9,8,7,6,5,4,3,2]), second = digit(`${root}${first}`, [6,5,4,3,2,9,8,7,6,5,4,3,2]); return `${root}${first}${second}`; }
function digit(value: string, weights: number[]) { const remainder = weights.reduce((sum, weight, index) => sum + Number(value[index]) * weight, 0) % 11; return remainder < 2 ? 0 : 11 - remainder; }
main().finally(() => db.$disconnect());
