import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/tenant/client";
import { protectPrivacySubject } from "../lib/erp/privacy-governance";

if (process.env.NALVEN_ALLOW_DEMO_PRIVACY_SEED !== "1") throw new Error("Defina NALVEN_ALLOW_DEMO_PRIVACY_SEED=1 para confirmar o seed demonstrativo de privacidade.");
const tenantUrl = process.env.TENANT_DATABASE_URL;
if (!tenantUrl) throw new Error("TENANT_DATABASE_URL é obrigatória.");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: tenantUrl }) }), DAY = 86_400_000, now = new Date();
const ago = (days: number) => new Date(now.valueOf() - days * DAY), ahead = (days: number) => new Date(now.valueOf() + days * DAY);

async function main() {
  const [identity] = await db.$queryRawUnsafe<Array<{ database: string; role: string }>>("SELECT current_database() AS database, current_user AS role");
  if (!identity || identity.database !== "nalven_t_demo" || identity.role !== "nalven_t_demo_runtime") throw new Error("O seed demonstrativo só pode executar em nalven_t_demo com a credencial runtime.");
  const profiles = await db.tenantUserProfile.findMany({ orderBy: { id: "asc" }, select: { userId: true, displayName: true } }), actors = profiles.map((item) => ({ id: item.userId, name: item.displayName || "Equipe demo" }));
  if (!actors.length) throw new Error("Execute primeiro o seed demonstrativo de usuários.");
  const actor = actors[0], reviewer = actors[1] || actor;
  await db.tenantSettings.upsert({ where: { id: 1 }, update: { dataProtectionOfficerName: "Marina Lopes", dataProtectionEmail: "privacidade@automais.demo", dataProtectionPhone: "(49) 3333-0101", privacySmallAgent: false, privacyDefaultRequestDays: 15, privacyProgramReviewAt: ahead(120), updatedBy: actor.name }, create: { id: 1, organizationName: "Auto Mais Peças", dataProtectionOfficerName: "Marina Lopes", dataProtectionEmail: "privacidade@automais.demo", dataProtectionPhone: "(49) 3333-0101", privacyDefaultRequestDays: 15, privacyProgramReviewAt: ahead(120), updatedBy: actor.name } });

  const bases = [
    { name: "Relacionamento comercial e cadastro", basis: "contract", purpose: "Cadastrar clientes, emitir pedidos, entregar produtos e prestar suporte pós-venda.", dataCategory: "Identificação e contato", dataSubjects: ["clientes", "representantes"], sourceSystems: ["ERP", "PDV", "CRM"], recipients: ["equipe comercial", "transportadoras"], owner: "Comercial" },
    { name: "Emissão e guarda fiscal", basis: "legal_obligation", purpose: "Emitir documentos fiscais e conservar registros exigidos pela legislação tributária.", dataCategory: "Fiscal e financeiro", dataSubjects: ["clientes", "fornecedores"], sourceSystems: ["ERP fiscal"], recipients: ["SEFAZ", "contabilidade"], owner: "Fiscal" },
    { name: "Análise e proteção de crédito", basis: "credit_protection", purpose: "Avaliar risco de inadimplência e administrar limites e cobranças.", dataCategory: "Financeiro", dataSubjects: ["clientes", "responsáveis financeiros"], sourceSystems: ["Financeiro", "CRM"], recipients: ["financeiro", "birôs autorizados"], owner: "Financeiro" },
    { name: "Campanhas por e-mail", basis: "consent", purpose: "Enviar novidades e ofertas conforme manifestação registrada e revogável.", dataCategory: "Contato e preferências", dataSubjects: ["clientes", "leads"], sourceSystems: ["CRM", "E-mail transacional"], recipients: ["marketing"], owner: "Marketing" },
    { name: "Prevenção a fraude no PDV", basis: "legitimate_interest", purpose: "Detectar comportamentos incompatíveis e proteger titulares e a operação contra fraude.", dataCategory: "Transacional e antifraude", dataSubjects: ["clientes", "operadores"], sourceSystems: ["PDV", "Auditoria"], recipients: ["prevenção a perdas"], owner: "Riscos" },
    { name: "Gestão de colaboradores", basis: "legal_obligation", purpose: "Cumprir obrigações trabalhistas, previdenciárias e de saúde e segurança.", dataCategory: "Recursos humanos", dataSubjects: ["colaboradores", "dependentes"], sourceSystems: ["ERP", "Contabilidade"], recipients: ["RH", "órgãos públicos"], owner: "Pessoas" },
  ];
  for (const row of bases) {
    const existing = await db.legalBasis.findFirst({ where: { name: row.name }, select: { id: true } });
    if (existing) await db.legalBasis.update({ where: { id: existing.id }, data: { ...row, recipients: row.recipients, dataSubjects: row.dataSubjects, sourceSystems: row.sourceSystems, active: true, reviewAt: ahead(180), updatedBy: actor.name } });
    else await db.legalBasis.create({ data: { ...row, recipients: row.recipients, dataSubjects: row.dataSubjects, sourceSystems: row.sourceSystems, active: true, reviewAt: ahead(180), updatedBy: actor.name } });
  }

  const retention = [
    ["Documentos fiscais", 1825, "Obrigação tributária e exercício regular de direitos.", "review", "Fiscal"],
    ["Cadastros comerciais inativos", 730, "Encerramento da relação e gestão de defesa em reclamações.", "anonymize", "Comercial"],
    ["Leads sem conversão", 180, "Necessidade e minimização após encerramento da prospecção.", "delete", "Marketing"],
    ["Registros de consentimento", 1825, "Prestação de contas sobre manifestações do titular.", "review", "Privacidade"],
    ["Imagens de segurança", 30, "Segurança do estabelecimento, salvo preservação por incidente.", "delete", "Operações"],
    ["Registros de incidentes", 1825, "Resolução CD/ANPD nº 15/2024 e prestação de contas.", "review", "Privacidade"],
  ] as const;
  for (const [dataCategory, retentionDays, legalReason, action, owner] of retention) await db.retentionRule.upsert({ where: { dataCategory }, update: { retentionDays, legalReason, action, owner, appliesTo: "Registros ativos e cópias controladas nos sistemas mapeados.", reviewAt: ahead(180), active: true, updatedBy: actor.name }, create: { dataCategory, retentionDays, legalReason, action, owner, appliesTo: "Registros ativos e cópias controladas nos sistemas mapeados.", reviewAt: ahead(180), active: true, updatedBy: actor.name } });

  const treatments = [
    { id: "privacy-treatment-customer-crm", name: "Cadastro e relacionamento com clientes", department: "Comercial", purpose: "Gerenciar propostas, pedidos, histórico de relacionamento e atendimento.", legalBasis: "contract", dataCategories: ["identificação", "contato", "histórico comercial"], dataSubjects: ["clientes", "representantes"], operations: ["coleta", "consulta", "atualização", "compartilhamento"], systems: ["ERP", "CRM"], recipients: ["vendas", "logística"], sensitiveData: false, childrenData: false, internationalTransfer: false, owner: "Gerência Comercial", riskLevel: "medium" },
    { id: "privacy-treatment-fiscal-documents", name: "Emissão e escrituração fiscal", department: "Fiscal", purpose: "Emitir, escriturar e conservar documentos fiscais eletrônicos.", legalBasis: "legal_obligation", dataCategories: ["identificação", "documento fiscal", "financeiro"], dataSubjects: ["clientes", "fornecedores"], operations: ["coleta", "transmissão", "armazenamento"], systems: ["ERP Fiscal", "SEFAZ"], recipients: ["SEFAZ", "contabilidade"], sensitiveData: false, childrenData: false, internationalTransfer: false, owner: "Coordenação Fiscal", riskLevel: "high" },
    { id: "privacy-treatment-credit-analysis", name: "Análise e concessão de crédito", department: "Financeiro", purpose: "Avaliar capacidade de pagamento e administrar exposição financeira.", legalBasis: "credit_protection", dataCategories: ["identificação", "financeiro", "score"], dataSubjects: ["clientes", "avalistas"], operations: ["consulta", "análise", "decisão"], systems: ["ERP Financeiro", "Birô"], recipients: ["financeiro", "birô de crédito"], sensitiveData: false, childrenData: false, internationalTransfer: false, owner: "Gerência Financeira", riskLevel: "high" },
    { id: "privacy-treatment-email-marketing", name: "Comunicação promocional", department: "Marketing", purpose: "Enviar campanhas segmentadas com base em consentimento demonstrável.", legalBasis: "consent", dataCategories: ["contato", "preferências", "interações"], dataSubjects: ["clientes", "leads"], operations: ["segmentação", "envio", "mensuração"], systems: ["CRM", "Plataforma de e-mail"], recipients: ["marketing", "operador de e-mail"], sensitiveData: false, childrenData: false, internationalTransfer: true, transferSafeguards: "Cláusulas contratuais e avaliação do operador internacional.", owner: "Marketing", riskLevel: "medium" },
    { id: "privacy-treatment-video-security", name: "Monitoramento por câmeras", department: "Operações", purpose: "Proteger pessoas, patrimônio e apoiar apuração de incidentes.", legalBasis: "legitimate_interest", dataCategories: ["imagem", "data e hora", "localização interna"], dataSubjects: ["clientes", "colaboradores", "visitantes"], operations: ["captura", "armazenamento", "consulta restrita"], systems: ["CFTV"], recipients: ["segurança", "autoridades mediante requisição"], sensitiveData: false, childrenData: true, internationalTransfer: false, owner: "Operações", riskLevel: "high" },
    { id: "privacy-treatment-human-resources", name: "Administração de pessoal", department: "Pessoas", purpose: "Gerenciar contrato de trabalho, benefícios e obrigações legais.", legalBasis: "legal_obligation", dataCategories: ["identificação", "financeiro", "saúde ocupacional"], dataSubjects: ["colaboradores", "dependentes"], operations: ["coleta", "uso", "compartilhamento", "retenção"], systems: ["ERP", "Folha"], recipients: ["RH", "contabilidade", "órgãos públicos"], sensitiveData: true, childrenData: true, internationalTransfer: false, owner: "Recursos Humanos", riskLevel: "critical" },
    { id: "privacy-treatment-delivery-logistics", name: "Entrega de pedidos", department: "Logística", purpose: "Endereçar, transportar e comprovar a entrega de mercadorias.", legalBasis: "contract", dataCategories: ["nome", "telefone", "endereço", "assinatura"], dataSubjects: ["clientes", "destinatários"], operations: ["consulta", "compartilhamento", "comprovação"], systems: ["ERP", "Transportadora"], recipients: ["expedição", "transportadoras"], sensitiveData: false, childrenData: false, internationalTransfer: false, owner: "Logística", riskLevel: "medium" },
    { id: "privacy-treatment-fraud-prevention", name: "Prevenção de fraude e abuso", department: "Riscos", purpose: "Detectar padrões de fraude, acessos suspeitos e abuso de descontos.", legalBasis: "legitimate_interest", dataCategories: ["identificadores", "eventos de acesso", "transações"], dataSubjects: ["clientes", "usuários"], operations: ["monitoramento", "correlação", "investigação"], systems: ["PDV", "Auditoria"], recipients: ["riscos", "segurança"], sensitiveData: false, childrenData: false, internationalTransfer: false, owner: "Riscos e Compliance", riskLevel: "high" },
  ];
  for (const row of treatments) await db.privacyTreatmentActivity.upsert({ where: { id: row.id }, update: { ...row, collectionSource: "Interação direta e sistemas corporativos", securityMeasures: "Controle de acesso por função, trilha de auditoria, criptografia e revisão periódica.", retentionSummary: "Conforme regra específica da categoria e obrigação legal aplicável.", status: "active", lastReviewedAt: ago(30), nextReviewAt: ahead(150), updatedBy: reviewer.name }, create: { ...row, collectionSource: "Interação direta e sistemas corporativos", securityMeasures: "Controle de acesso por função, trilha de auditoria, criptografia e revisão periódica.", retentionSummary: "Conforme regra específica da categoria e obrigação legal aplicável.", status: "active", lastReviewedAt: ago(30), nextReviewAt: ahead(150), createdBy: actor.name, updatedBy: reviewer.name } });

  const assessments = [
    { id: "privacy-ripd-human-resources", treatmentId: "privacy-treatment-human-resources", title: "RIPD · Administração de pessoal", status: "approved", inherentRisk: "critical", residualRisk: "medium", reason: "Tratamento contínuo de dados de saúde ocupacional e dados de dependentes.", risks: ["acesso indevido", "compartilhamento excessivo", "retenção além do necessário"], safeguards: ["segregação de acesso", "criptografia", "retenção documentada", "revisão anual"], dpoOpinion: "Salvaguardas adequadas, condicionadas à revisão anual de acessos e operadores." },
    { id: "privacy-ripd-video-security", treatmentId: "privacy-treatment-video-security", title: "RIPD · Monitoramento por câmeras", status: "in_review", inherentRisk: "high", residualRisk: "medium", reason: "Monitoramento sistemático de área acessível ao público e possível captura de vulneráveis.", risks: ["uso incompatível", "acesso não autorizado", "retenção excessiva"], safeguards: ["sinalização", "prazo de 30 dias", "acesso restrito"], dpoOpinion: null },
    { id: "privacy-ripd-credit", treatmentId: "privacy-treatment-credit-analysis", title: "RIPD · Decisão de crédito", status: "approved", inherentRisk: "high", residualRisk: "low", reason: "Avaliação que pode impactar acesso do titular a condições comerciais.", risks: ["decisão incorreta", "dados desatualizados", "falta de transparência"], safeguards: ["revisão humana", "canal de contestação", "fonte documentada"], dpoOpinion: "Aprovado com revisão humana obrigatória para bloqueios." },
    { id: "privacy-ripd-fraud", treatmentId: "privacy-treatment-fraud-prevention", title: "RIPD · Monitoramento antifraude", status: "draft", inherentRisk: "high", residualRisk: "medium", reason: "Correlação de eventos e transações para identificação de comportamentos suspeitos.", risks: ["falso positivo", "monitoramento desproporcional"], safeguards: ["minimização", "revisão humana", "limite de acesso"], dpoOpinion: null },
  ];
  for (const row of assessments) await db.privacyImpactAssessment.upsert({ where: { id: row.id }, update: { ...row, necessity: "O tratamento atende finalidade documentada e não há alternativa menos intrusiva com eficácia equivalente.", proportionality: "Os dados e o prazo são limitados ao necessário, com revisão periódica.", approvedBy: row.status === "approved" ? reviewer.name : null, approvedAt: row.status === "approved" ? ago(20) : null, reviewAt: ahead(180), updatedBy: reviewer.name }, create: { ...row, necessity: "O tratamento atende finalidade documentada e não há alternativa menos intrusiva com eficácia equivalente.", proportionality: "Os dados e o prazo são limitados ao necessário, com revisão periódica.", approvedBy: row.status === "approved" ? reviewer.name : null, approvedAt: row.status === "approved" ? ago(20) : null, reviewAt: ahead(180), createdBy: actor.name, updatedBy: reviewer.name } });

  const requests = [
    ["LGPD-DEMO-0001", "access", "Ana Martins", "52998224725", "ana.martins@example.com", "in_progress", "high", ago(7), ahead(8)],
    ["LGPD-DEMO-0002", "correction", "Bruno Alves", "11144477735", "49999991122", "verified", "normal", ago(3), ahead(12)],
    ["LGPD-DEMO-0003", "deletion", "Carla Souza", "93541134780", "carla.souza@example.com", "identity_pending", "urgent", ago(13), ahead(2)],
    ["LGPD-DEMO-0004", "portability", "Diego Rocha", "98765432000198", "diego@empresa.demo", "received", "normal", ago(1), ahead(14)],
    ["LGPD-DEMO-0005", "revocation", "Elisa Prado", "39053344705", "49988887766", "completed", "normal", ago(19), ago(4)],
    ["LGPD-DEMO-0006", "info_sharing", "Fábio Lima", "16899535009", "fabio.lima@example.com", "completed", "normal", ago(24), ago(9)],
    ["LGPD-DEMO-0007", "objection", "Gabriela Nunes", "86288366757", "49977776655", "rejected", "high", ago(22), ago(7)],
    ["LGPD-DEMO-0008", "anonymization", "Henrique Moraes", "98765432000198", "henrique@empresa.demo", "in_progress", "high", ago(12), ahead(3)],
    ["LGPD-DEMO-0009", "restriction", "Isabela Reis", "52998224725", "isabela.reis@example.com", "received", "normal", ago(2), ahead(13)],
    ["LGPD-DEMO-0010", "access", "João Costa", "11144477735", "49966665544", "completed", "normal", ago(35), ago(20)],
    ["LGPD-DEMO-0011", "correction", "Lara Dias", "93541134780", "lara.dias@example.com", "in_progress", "urgent", ago(16), ago(1)],
    ["LGPD-DEMO-0012", "access", "Marcos Pires", "39053344705", "49955554433", "verified", "normal", ago(5), ahead(10)],
  ] as const;
  for (const [index, row] of requests.entries()) {
    const [number, type, subjectName, document, contact, status, priority, createdAt, dueAt] = row;
    if (await db.privacyRequest.findUnique({ where: { number }, select: { id: true } })) continue;
    const protectedSubject = protectPrivacySubject(document, contact), final = status === "completed" || status === "rejected", created = await db.privacyRequest.create({ data: { number, type, subjectName, ...protectedSubject, channel: contact.includes("@") ? "email" : "phone", priority, requesterRelation: "self", status, dueAt, verifiedAt: ["verified", "in_progress", "completed"].includes(status) ? new Date(createdAt.valueOf() + DAY) : null, completedAt: final ? new Date(Math.min(now.valueOf(), createdAt.valueOf() + 10 * DAY)) : null, identityMethod: ["verified", "in_progress", "completed"].includes(status) ? "Documento e confirmação pelo canal cadastrado" : null, evidence: status === "completed" ? `EVID-DEMO-${index + 1}` : null, responseSummary: status === "completed" ? "Resposta disponibilizada ao titular no canal verificado." : null, rejectionReason: status === "rejected" ? "Pedido não atendido integralmente em razão de obrigação legal de conservação; justificativa comunicada." : null, assignedTo: actors[index % actors.length].name, createdBy: actor.name, createdAt } });
    await db.privacyRequestEvent.createMany({ data: [{ requestId: created.id, kind: "created", toStatus: "received", note: "Solicitação recebida no canal de privacidade.", actorId: actor.id, actorName: actor.name, createdAt }, ...(status !== "received" ? [{ requestId: created.id, kind: "status_changed", fromStatus: "received", toStatus: status, note: "Etapa simulada para demonstração operacional.", actorId: reviewer.id, actorName: reviewer.name, createdAt: new Date(createdAt.valueOf() + DAY) }] : [])] });
  }

  const incidents = [
    { title: "Planilha enviada ao destinatário incorreto", severity: "high", status: "notifying", affectedSubjects: 18, riskRelevant: true, categories: ["nome", "e-mail", "histórico de compras"], detectedAt: ago(1), anpd: null, subjects: null, reason: "Dados de contato e histórico comercial permitem perfilamento dos titulares." },
    { title: "Tentativas automatizadas de acesso ao portal", severity: "medium", status: "contained", affectedSubjects: 0, riskRelevant: false, categories: ["identificadores técnicos"], detectedAt: ago(4), anpd: null, subjects: null, reason: "Não houve confirmação de acesso a dados pessoais; logs e monitoramento foram preservados." },
    { title: "Exposição temporária de comprovantes", severity: "critical", status: "resolved", affectedSubjects: 42, riskRelevant: true, categories: ["documento", "endereço", "dados financeiros"], detectedAt: ago(40), anpd: ago(38), subjects: ago(38), reason: "Documentos financeiros ficaram acessíveis sem autenticação por período limitado." },
    { title: "Dispositivo corporativo extraviado", severity: "high", status: "assessing", affectedSubjects: 120, riskRelevant: true, categories: ["contatos comerciais"], detectedAt: ago(2), anpd: null, subjects: null, reason: "O equipamento continha cache corporativo; análise de criptografia em andamento." },
    { title: "Documento impresso descartado incorretamente", severity: "low", status: "resolved", affectedSubjects: 1, riskRelevant: false, categories: ["identificação"], detectedAt: ago(65), anpd: null, subjects: null, reason: "Documento recuperado imediatamente em área restrita, sem acesso por terceiro." },
  ];
  for (const [index, row] of incidents.entries()) {
    if (await db.privacyIncident.findFirst({ where: { title: row.title }, select: { id: true } })) continue;
    const notificationDueAt = row.riskRelevant ? new Date(row.detectedAt.valueOf() + 3 * DAY) : null, created = await db.privacyIncident.create({ data: { title: row.title, severity: row.severity, description: "Cenário demonstrativo para exercitar avaliação, contenção, comunicação e encerramento.", status: row.status, affectedSubjects: row.affectedSubjects, riskRelevant: row.riskRelevant, dataCategories: row.categories, detectedAt: row.detectedAt, notificationDueAt, containedAt: ["contained", "notifying", "resolved"].includes(row.status) ? new Date(row.detectedAt.valueOf() + 4 * 3_600_000) : null, anpdNotifiedAt: row.anpd, subjectsNotifiedAt: row.subjects, rootCause: row.status === "resolved" ? "Falha de processo identificada e documentada." : null, containmentMeasures: ["contained", "notifying", "resolved"].includes(row.status) ? "Acesso interrompido, evidências preservadas e credenciais revisadas." : null, correctiveActions: row.status === "resolved" ? "Controle revisado, orientação aplicada e monitoramento reforçado." : null, decisionReason: row.reason, assignedTo: actors[index % actors.length].name, reportedAt: row.detectedAt, resolvedAt: row.status === "resolved" ? new Date(row.detectedAt.valueOf() + 5 * DAY) : null, createdBy: actor.name } });
    await db.privacyIncidentEvent.createMany({ data: [{ incidentId: created.id, kind: "created", toStatus: "open", note: row.reason, actorId: actor.id, actorName: actor.name, createdAt: row.detectedAt }, ...(row.status !== "open" ? [{ incidentId: created.id, kind: "status_changed", fromStatus: "open", toStatus: row.status, note: "Resposta simulada para demonstração da central.", actorId: reviewer.id, actorName: reviewer.name, createdAt: new Date(row.detectedAt.valueOf() + 3_600_000) }] : [])] });
  }
  const seedAudit = await db.tenantAuditEvent.findFirst({ where: { correlationId: "privacy-demo-seed", action: "privacy.demo_dataset.refreshed" }, select: { id: true } });
  if (!seedAudit) await db.tenantAuditEvent.create({ data: { actorId: actor.id, action: "privacy.demo_dataset.refreshed", entityType: "privacy_governance", entityId: "demo", correlationId: "privacy-demo-seed", afterData: { bases: bases.length, retention: retention.length, treatments: treatments.length, assessments: assessments.length, requests: requests.length, incidents: incidents.length } } });
  console.log(JSON.stringify({ bases: await db.legalBasis.count(), retention: await db.retentionRule.count(), treatments: await db.privacyTreatmentActivity.count(), assessments: await db.privacyImpactAssessment.count(), requests: await db.privacyRequest.count(), requestEvents: await db.privacyRequestEvent.count(), incidents: await db.privacyIncident.count(), incidentEvents: await db.privacyIncidentEvent.count() }));
}

main().finally(async () => db.$disconnect());
