"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Rule={source:string;destination:string;status:number;active:boolean};
type Report={rules:Rule[];counts:Array<{status:number;_count:number}>;paths:Array<{path:string;destination:string;status:number;_count:number;_max:{createdAt:string}}> ;recent:Array<{id:string;path:string;destination:string;status:number;createdAt:string}>;coverage:Array<{path:string;title:string;description:string;canonical:string;robots:string;redirect:string|null}>;aliases:string[];origin:string;generatedAt:string;retentionDays:number};
export default function NavigationDashboard(){
 const [data,setData]=useState<Report>(),[days,setDays]=useState("7"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[editing,setEditing]=useState<Rule>(),[query,setQuery]=useState("");
 const load=useCallback(async()=>{setError("");try{const r=await fetch(`/api/admin/navigation?days=${days}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao consultar o monitoramento.");setData(d)}catch(e){setError(e instanceof Error?e.message:"Falha de conexão.")}},[days]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const f=new FormData(form);setBusy(true);setNotice("");try{const r=await fetch('/api/admin/navigation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source:f.get('source'),destination:f.get('destination'),status:Number(f.get('status')),active:f.get('active')==='on'})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao salvar.");setEditing(undefined);form.reset();setNotice("Redirecionamento salvo, auditado e em vigor.");await load()}catch(e){setNotice(e instanceof Error?e.message:"Falha de conexão.")}finally{setBusy(false)}}
 return <div className="navigation-page"><div className="module-heading"><div><p>SAÚDE DOS ENDEREÇOS</p><h1>Redirects e erros 404</h1><span>Ocorrências registradas pelo servidor e destinos publicados.</span></div><div className="page-actions"><select aria-label="Período" value={days} onChange={e=>setDays(e.target.value)}><option value="1">Últimas 24 horas</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select><button onClick={load}>Atualizar</button></div></div>{error&&<p role="alert" className="module-error">{error}</p>}{notice&&<p role="status" className="navigation-notice">{notice}</p>}{!data?<p>{error?"Os dados não estão disponíveis. Tente atualizar.":"Consultando registros…"}</p>:<>
 <section className="metric-grid">{[["Erros 404",data.counts.filter(x=>x.status===404).reduce((n,x)=>n+x._count,0)],["Redirecionamentos",data.counts.filter(x=>x.status>=300&&x.status<400).reduce((n,x)=>n+x._count,0)],["Regras ativas",data.rules.filter(x=>x.active).length],["Páginas publicadas",data.coverage.length]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</section>
 <p className="navigation-caption">Atualizado em {new Date(data.generatedAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}. Retenção de {data.retentionDays} dias. Contagem de requisições, incluindo robôs; não representa visitantes únicos. Parâmetros, IPs e tokens de acesso não são armazenados. Redirecionamentos do proxy externo não estão incluídos.</p>
 <div className="navigation-grid"><section className="control-panel"><header><h2>{editing?"Editar redirecionamento":"Novo redirecionamento"}</h2></header><form className="content-form" key={editing?.source||"new"} onSubmit={save}><label>Endereço de origem<input name="source" required maxLength={500} placeholder="/endereco-antigo" defaultValue={editing?.source} readOnly={!!editing}/></label><label>Destino publicado<select name="destination" required defaultValue={editing?.destination||"/"}>{data.coverage.map(page=><option key={page.path}>{page.path}</option>)}</select></label><label>Tipo<select name="status" defaultValue={editing?.status||308}><option value="308">308 — Permanente</option><option value="301">301 — Permanente</option><option value="307">307 — Temporário</option><option value="302">302 — Temporário</option></select></label><label className="navigation-check"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/>Regra ativa</label><p>URLs de autenticação são protegidas. Destinos externos e ciclos são rejeitados.</p><div><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar regra"}</button>{editing&&<button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button>}</div></form></section><section className="control-panel"><header><h2>Regras publicadas</h2></header><div className="navigation-rules">{data.rules.map(rule=><button key={rule.source} onClick={()=>setEditing(rule)}><strong>{rule.source}</strong><span>→ {rule.destination}</span><small>{rule.status} · {rule.active?"Ativa":"Desativada"} · Editar</small></button>)}{!data.rules.length&&<p>Nenhuma regra personalizada. Use uma ocorrência 404 abaixo para criar a primeira.</p>}</div><details><summary>{data.aliases.length} alternativas de login → /login</summary>{data.aliases.map(path=><p key={path}><code>{path}</code> → /login · 308</p>)}</details></section></div>
 <section className="control-panel"><header><div><h2>Endereços com ocorrências</h2><p>Até 100 combinações mais frequentes no período.</p></div><input aria-label="Filtrar endereços" placeholder="Buscar endereço…" value={query} onChange={e=>setQuery(e.target.value)}/></header><div className="admin-table-wrap"><table><thead><tr><th>Endereço</th><th>HTTP</th><th>Destino</th><th>Ocorrências</th><th>Última ocorrência</th><th>Ação</th></tr></thead><tbody>{data.paths.filter(row=>row.path.includes(query)).map(row=><tr key={`${row.path}:${row.status}:${row.destination}`}><td><code>{row.path}</code></td><td>{row.status}</td><td>{row.destination||"—"}</td><td>{row._count}</td><td>{new Date(row._max.createdAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}</td><td>{row.status===404&&<button onClick={()=>{setEditing({source:row.path,destination:"/",status:308,active:true});window.scrollTo({top:0,behavior:"smooth"})}}>Criar redirect</button>}</td></tr>)}</tbody></table>{!data.paths.length&&<p className="empty-state">Nenhuma ocorrência registrada neste período. Os dados aparecerão conforme o site receber acessos.</p>}</div></section>
 <section className="control-panel"><header><div><h2>Cobertura de SEO</h2><p>Metadados efetivos das páginas públicas.</p></div><Link href="/admin/seo">Editar metadados →</Link></header><div className="navigation-links"><a href="/sitemap.xml" target="_blank" rel="noreferrer">Sitemap XML ↗</a><a href="/robots.txt" target="_blank" rel="noreferrer">Robots.txt ↗</a><a href="/opengraph-image" target="_blank" rel="noreferrer">Imagem social ↗</a></div><div className="admin-table-wrap"><table><thead><tr><th>Página</th><th>Título e descrição</th><th>Canonical</th><th>Indexação</th></tr></thead><tbody>{data.coverage.map(page=><tr key={page.path}><td><a href={page.path} target="_blank" rel="noreferrer">{page.path}</a></td><td><strong>{page.title||"Título ausente"}</strong><small>{page.description||"Descrição ausente"}</small></td><td>{page.canonical}</td><td>{page.redirect?`Redirect → ${page.redirect}`:page.robots}</td></tr>)}</tbody></table></div></section>
 </>}</div>;
}
